---
title: "Fig.S11"
output: html_document
---

### Fig.S11A

```{r,message=F,warning=F,height = 3,width = 10}
library(maftools)
library(openxlsx)
library(ComplexHeatmap)
library(reshape2)
library(dplyr)
library(ggplot2)
source("data/oncomatrix.R")

maf=read.maf("data/TableS3_AllSample_Mutation_addPeptide.maf")

mt_df=read.xlsx("data/Mutation_peptide_Sample_data.xlsx")
mt_df=mt_df[!is.element(mt_df$Gene_Symbol,c("DBR1","ISG15")),]
mt_gn=unique(mt_df$Gene_Symbol)
mt_dat=acast(mt_df,Gene_Symbol~variable)
mt_dat[is.na(mt_dat)]=""
mt_dat[mt_dat!=""]="*"
colnames(mt_dat)=gsub("MS_|_TCa","",colnames(mt_dat))

#sample order
pst_ord=c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST",
         "PCA-05-PST","PCA-06-PST")
dac_ord=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4","DAC5",
         "DAC50","DAC53","DAC57","DAC69")
pdx_ord=c("CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
         "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080",
         "CH-17-0087","CH-17-0091")
tcc_ord=c("TCC-01","TCC-02","TCC-03")
sp_ord=c(pst_ord,dac_ord,pdx_ord,tcc_ord)

maf=subsetMaf(maf,tsb=sp_ord,genes=mt_gn)
om = createOncoMatrix(m = maf,g=mt_gn)
numMat=om$numericMatrix
##基因顺序
row_sum=rowSums(numMat!=0)
gn_ord=names(row_sum)[order(row_sum,decreasing = T)]

ht_dt=om$oncoMatrix
ht_dt[ht_dt==""]=NA
ht_dt=ht_dt[,do.call(order,as.data.frame(t(ht_dt)))]
df=ht_dt
df[is.na(df)]=""

mut_freq1=rowSums(numMat[gn_ord,intersect(pst_ord,colnames(numMat))]!=0)/length(pst_ord)
mut_freq2=rowSums(numMat[gn_ord,intersect(dac_ord,colnames(numMat))]!=0)/length(dac_ord)
mut_freq3=rowSums(numMat[gn_ord,intersect(pdx_ord,colnames(numMat))]!=0)/length(pdx_ord)
mut_freq4=rowSums(numMat[gn_ord,intersect(tcc_ord,colnames(numMat))]!=0)/length(tcc_ord)

#save(wf_dt,tmb,sp_ord,gn_ord,mut_freq,file="res/Peptide_warterfall_data_HLA修正.Rdata")
ht_ft=cbind(df,matrix("",nrow=nrow(df),ncol=length(setdiff(sp_ord,colnames(df)))))
colnames(ht_ft)[20:33]=setdiff(sp_ord,colnames(df))

cell_ft=cbind(mt_dat,matrix("",nrow=nrow(mt_dat),ncol=length(setdiff(sp_ord,colnames(mt_dat)))))
colnames(cell_ft)[15:35]=setdiff(sp_ord,colnames(mt_dat))

#just MS,not grep mutation
cell_ft["NOL11","DAC73"]=""
cell_ft["FOXO1","CH-17-0072"]=""

#Primary PCa
mt_df$Disease="Primary PCa"
mt_df$Disease[grep("MS_CH-",mt_df$variable)]="CCA PDXs"
mt_df$Disease[grep("MS_TCC",mt_df$variable)]="TC"
mt_df$Disease[mt_df$variable=="MS_PCA-06-CILN-L"|mt_df$variable=="MS_PCA-06-IILN-R"]="Metastasis PCa"

mt_df_pri=dcast(mt_df[mt_df$Disease!="Metastasis PCa",],Peptide+Gene_Symbol+AAchange~Disease,fun.aggregate = length)
mt_df_pri$AAchange=paste0(gsub("[0-9]*|\\/.*","",mt_df_pri$AAchange),
                          gsub("[A-Z]*|\\/","",mt_df_pri$AAchange),
                          gsub(".*\\/","",mt_df_pri$AAchange))
mt_df_pri=mt_df_pri[match(gn_ord,mt_df_pri$Gene_Symbol),]
mt_df_pri$`PC organoids`=0
mt_df_pri$`CCA PDXs`[mt_df_pri$AAchange=="A511V"]=0

col<-c("#13a983","#3f60aa","#44c1f0","#e8490f","#f18800","#e4ce00","#9ec417","blue","#631879FF","red","black")
names(col)=c("Missense_Mutation","Frame_Shift_Del" ,"Nonsense_Mutation","In_Frame_Del","In_Frame_Ins","Translation_Start_Site","Frame_Shift_Ins","Nonstop_Mutation","Multi_Hit","Splice_Site","Del")

hl=rowAnnotation(Gene=anno_text(mt_df_pri$Gene_Symbol,gp=gpar(fontsize=8)),
                 AAchange=anno_text(mt_df_pri$AAchange,gp=gpar(fontsize=8)),
                 Peptide_N=anno_barplot(mt_df_pri[,c("Primary PCa","PC organoids","CCA PDXs","TC")],
                                        gp=gpar(fill= c(PST="#4141D1","PC organoids"="grey","CCA PDXs"="#0a9a63","TC"="#fe7f00")),
                                        axis_param = list(direction="reverse")))

hr1=rowAnnotation(Frequency=anno_barplot(mut_freq1[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq1[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht1=Heatmap(ht_ft[gn_ord,pst_ord],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr1,height = unit(length(gn_ord)*0.25,"cm"),width = unit(length(pst_ord)*0.25,"cm"),
                 column_split = rep("Primary PCa",6),left_annotation = hl,
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 cell_fun=function(j, i,x,y,  width, height, fill) {
                   # since grid.text can also be vectorized
                   grid.text(as.matrix(cell_ft[gn_ord,pst_ord])[i,j], x, y,hjust=0.5,vjust=0.8 ,
                             gp = gpar(fontsize = 8,col="white"))},
                 row_labels = mt_df_pri$Peptide)

hr2=rowAnnotation(Frequency=anno_barplot(mut_freq2[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq2[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht2=Heatmap(ht_ft[gn_ord,dac_ord],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr2,height = unit(length(gn_ord)*0.25,"cm"),width = unit(length(dac_ord)*0.25,"cm"),
                 column_split = rep("PC organoids",11),
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 cell_fun=function(j, i,x,y,  width, height, fill) {
                   # since grid.text can also be vectorized
                   grid.text(as.matrix(cell_ft[gn_ord,dac_ord])[i,j], x, y,hjust=0.5,vjust=0.8 ,
                             gp = gpar(fontsize = 8,col="white"))})
hr3=rowAnnotation(Frequency=anno_barplot(mut_freq3[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq3[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht3=Heatmap(ht_ft[gn_ord,pdx_ord],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr3,height = unit(length(gn_ord)*0.25,"cm"),width = unit(length(pdx_ord)*0.25,"cm"),
                 column_split = rep("CCA PDXs",13),
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 cell_fun=function(j, i,x,y,  width, height, fill) {
                   # since grid.text can also be vectorized
                   grid.text(as.matrix(cell_ft[gn_ord,pdx_ord])[i,j], x, y,hjust=0.5,vjust=0.8 ,
                             gp = gpar(fontsize = 8,col="white"))})
hr4=rowAnnotation(Frequency=anno_barplot(mut_freq4[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq4[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht4=Heatmap(ht_ft[gn_ord,tcc_ord],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr4,height = unit(length(gn_ord)*0.25,"cm"),width = unit(length(tcc_ord)*0.25,"cm"),
                 column_split = rep("TC",3),
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 cell_fun=function(j, i,x,y,  width, height, fill) {
                   # since grid.text can also be vectorized
                   grid.text(as.matrix(cell_ft[gn_ord,tcc_ord])[i,j], x, y,hjust=0.5,vjust=0.8 ,
                             gp = gpar(fontsize = 8,col="white"))})

plot_ht1+plot_ht2+plot_ht3+plot_ht4
```

### Fig.S4B

```{r,message=F,warning=F,height = 3,width = 8}
sp_file=read.xlsx("data/CPGEA_oncoprint_gene_tab_data.xlsx")
maf=read.maf("data/CPGEA_Somatic_mutation.filter.208.maf", removeDuplicatedVariants = F)
sp_all=sp_file$Sample
maf=subsetMaf(maf,genes=mt_gn,tsb = paste(sp_all,"_WGS",sep=""))
om = createOncoMatrix(m = maf,g=mt_gn)
numMat=om$numericMatrix

ht_dt=om$oncoMatrix
ht_dt[ht_dt==""]=NA
ht_dt=ht_dt[,do.call(order,as.data.frame(t(ht_dt)))]
df=ht_dt
df[is.na(df)]=""

mut_freq5=rowSums(numMat[,]!=0)/(length(sp_all)+2)
mut_freq5=c(mut_freq5,rep(0,length(setdiff(gn_ord,rownames(numMat)))))
names(mut_freq5)=c(rownames(numMat),setdiff(gn_ord,rownames(numMat)))

colnames(df)=sub("_WGS","",colnames(df))
plot_df5=cbind(df,matrix("",nrow=nrow(numMat),ncol=length(setdiff(sp_all,colnames(df))[1:3])))
colnames(plot_df5)=c(colnames(df),setdiff(sp_all,colnames(df))[1:3])
plot_df5=rbind(plot_df5,matrix("",nrow=length(setdiff(gn_ord,rownames(df))),ncol=ncol(plot_df5)))
rownames(plot_df5)=c(rownames(df),setdiff(gn_ord,rownames(df)))

hr5=rowAnnotation(Frequency=anno_barplot(mut_freq5[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq5[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht5=Heatmap(plot_df5[gn_ord,],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr5,height = unit(length(gn_ord)*0.25,"cm"),width = unit(ncol(plot_df5)*0.25,"cm"),
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 column_title = "CPGEA (208 Samples)"
)
print(plot_ht5)
```

### Fig.S4C

```{r,message=F,warning=F,height = 3,width = 8}
maf=read.maf("data/PAAD_functional+validation.maf", removeDuplicatedVariants = F)

sp_all=levels(maf@data$Tumor_Sample_Barcode)
#maf=subsetMaf(maf,genes=mt_gn,tsb = sp_all)
#om = createOncoMatrix(m = maf,g=mt_gn)
#numMat=om$numericMatrix


mut_freq6=rep(0,length(mt_gn))
names(mut_freq6)=gn_ord
plot_df6=ht_ft[gn_ord,dac_ord]
colnames(plot_df6)=sp_all[1:11]
hr6=rowAnnotation(Frequency=anno_barplot(mut_freq6[gn_ord],gp=gpar(fill="#197EC0FF"),axis_param = list(side="top")),
                  freq=anno_text(paste(round(mut_freq6[gn_ord],3)*100,"%",sep=""),gp=gpar(fontsize=8)))
plot_ht6=Heatmap(plot_df6[gn_ord,],col = col,cluster_rows = F,cluster_columns = F,
                 na_col = "white",border_gp = gpar(col="black"),column_names_side = "top",
                 right_annotation = hr6,height = unit(length(gn_ord)*0.25,"cm"),width = unit(ncol(plot_df5)*0.25,"cm"),
                 row_names_side = "left",row_names_gp = gpar(fontsize=8),column_names_gp = gpar(fontsize=8),name="Mutation",
                 column_title = "PAAD (69 Samples)"
)
print(plot_ht6)
```

### Fig.S4D
```{r,message=F,warning=F,height = 2.5,width = 4}
maf=read.maf("data/TableS3_AllSample_Mutation_addPeptide.maf")
mt_df=read.xlsx("data/Mutation_peptide_Sample_data.xlsx")
mt_df=mt_df[!is.element(mt_df$Gene_Symbol,c("DBR1","ISG15")),]
mt_gn=unique(mt_df$Gene_Symbol)
mt_dat=acast(mt_df,Gene_Symbol~variable)
mt_dat[is.na(mt_dat)]=""
mt_dat[mt_dat!=""]="*"
colnames(mt_dat)=gsub("MS_|_TCa","",colnames(mt_dat))

#sample order
ms_pst=c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST",
         "PCA-05-PST","PCA-06-PST")
ms_dac=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4","DAC5",
         "DAC50","DAC53","DAC57","DAC69")
ms_pdx=c("CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
         "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080",
         "CH-17-0087","CH-17-0091")
ms_tcc=c("TCC-01","TCC-02","TCC-03")
sp_ord=c(ms_pst,ms_dac,ms_pdx,ms_tcc)
maf=subsetMaf(maf,tsb=sp_ord,genes=mt_gn)
om = createOncoMatrix(m = maf,g=mt_gn)
numMat=om$numericMatrix

##gene order
row_sum=rowSums(numMat!=0)
gn_ord=names(row_sum)[order(row_sum,decreasing = T)]

ht_dt=om$oncoMatrix
ht_dt[ht_dt==""]=NA
ht_dt=ht_dt[,do.call(order,as.data.frame(t(ht_dt)))]
df=ht_dt
df[is.na(df)]=""

mut_freq=rowSums(numMat[gn_ord,]!=0)/length(sp_ord)

wf_dt=as.data.frame(t(df))[sp_ord,gn_ord]
rownames(wf_dt)=sp_ord
wf_dt=t(wf_dt)
wf_dt[is.na(wf_dt)]=""

ht_ft=cbind(df,matrix("",nrow=nrow(df),ncol=length(setdiff(sp_ord,colnames(df)))))
colnames(ht_ft)[20:33]=setdiff(sp_ord,colnames(df))

cell_ft=cbind(mt_dat,matrix("",nrow=nrow(mt_dat),ncol=length(setdiff(sp_ord,colnames(mt_dat)))))
colnames(cell_ft)[15:35]=setdiff(sp_ord,colnames(mt_dat))
cell_ft=cell_ft[,colnames(ht_ft)]

col<-c("#13a983","#3f60aa","#44c1f0","#e8490f","#f18800","#e4ce00","#9ec417","blue","#631879FF","red","black")
names(col)=c("Missense_Mutation","Frame_Shift_Del" ,"Nonsense_Mutation","In_Frame_Del","In_Frame_Ins","Translation_Start_Site","Frame_Shift_Ins","Nonstop_Mutation","Multi_Hit","Splice_Site","Del")
disease_colors <- c("NoPeptide"="grey80","Primary PCa"="#4141D1","CCA PDXs"="#0a9a63","TC"="#fe7f00")


#bar plot
maf_data=as.data.frame(maf@data)
maf_data=maf_data[is.element(maf_data$Tumor_Sample_Barcode,colnames(ht_ft)),]
maf_data$Disease[maf_data$Disease=="Prostate"]="Primary PCa"
maf_data$Disease[maf_data$Disease=="GWA"]="TC"
maf_data$Disease[maf_data$Disease=="PDX"]="CCA PDXs"

maf_data$p_col=ifelse(is.na(maf_data$Peptide),"grey80",disease_colors[maf_data$Disease])
maf_data$Disease[is.na(maf_data$Peptide)]="NoPeptide"

summary_by_type <- maf_data %>%
  group_by(Hugo_Symbol) %>%
  summarise(
    mean_freq = mean(VAF),
    sd_freq = sd(VAF),
    n = n(),
    .groups = 'drop'
  )


p1 <- ggplot(maf_data, aes(x = factor(Hugo_Symbol,levels = gn_ord),col=Disease, y = VAF)) +
  geom_point(data= maf_data[is.na(maf_data$Peptide),],position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.7),
             shape = 20, color="grey80",
             size = 1.5,alpha=0.8) +
  geom_point(data= maf_data[!is.na(maf_data$Peptide),],position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.7),
             shape = 20, 
             size = 1.5,alpha=0.8)+
  geom_text(data= maf_data[!is.na(maf_data$Peptide),], aes(x = factor(Hugo_Symbol,levels = gn_ord), y =VAF,label=sub("p\\.","",HGVSp_Short)),
            position = position_jitterdodge(jitter.width = 0.3, dodge.width = 0.7),
            size = 2,hjust=0.5,vjust=-0.2,col="black")+scale_color_manual(values=disease_colors)+
  # 标签
  labs(x = '',
       y = 'VAF') +
  # 主题
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = 'bold', hjust = 0.5),
    plot.subtitle = element_text(size = 11, hjust = 0.5, color = 'gray40'),
    axis.line.x = element_line(color = 'black', linewidth = 0.5),
    axis.line.y = element_line(color = 'black', linewidth = 0.5),
    axis.title = element_text(size = 11, face = 'bold'),
    axis.text = element_text(size = 11),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = 'right',
    legend.title = element_text(face = 'bold'),
    axis.text.x = element_text(size = 9,angle=90,hjust=1,vjust=0.5),
    axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),axis.ticks = element_line()
  )
p1
```

### Fig.S4E
```{r,message=F,warning=F,height = 3,width = 5.6}
library(openxlsx)
#set colors
Region_lev=c("InternalORF","ncRNA","5'UTR","3'UTR","LowConfidence\nExon","IGR","uORF","5_extension","dORF")
Region_col=c("#57b1d4","#9ed9e9","#55b85d","#b2d59b","#e2e560","#e9eca9","#dc8d42","#ddba90","#626dad")
names(Region_col)=Region_lev
Region_col=c(Region_col,"5' Overlap uORF"="lightpink","3' Overlap dORF"="lightgreen")

#science ORF
science=read.xlsx("data/science.adk3487_tables_s1_to_s14 2.xlsx",sheet = "ST6_ncHLAp PDAC PDO  ",startRow = 2)
sub_sci=unique(science[,c("seq_upper","filename","biotype","hh_ip_detection","ribo_detection","thymus_ip_detection","cancer_restricted")])

#remove hh,ribo,thymu
sub_sci=sub_sci[sub_sci$hh_ip_detection==F&sub_sci$ribo_detection==F&sub_sci$thymus_ip_detection==F,]

sub_sci_uni=unique(sub_sci[,-2])

#uniform define
sci_type=as.data.frame(table(sub_sci_uni$biotype))
sci_type$Region=as.character(sci_type$Var1)
sci_type$Region[sci_type$Region=="Antisense"|sci_type$Region=="lincRNA"|sci_type$Region=="ncRNA Processed Transcript"|sci_type$Region=="ncRNA Retained Intron"|sci_type$Region=="Pseudogene"|sci_type$Region=="TUCP"]="ncRNA"
sci_type$Region[sci_type$Region=="Nonsense Mediated Decay"]="LowConfidence\nExon"
sci_type$Region[sci_type$Region=="Out-of-Frame (intORF)"]="InternalORF"
sci_type$Region[sci_type$Region=="3' dORF"]="dORF"
sci_type$Region[sci_type$Region=="5' uORF"]="uORF"
sci_type=sci_type%>%group_by(Region)%>%summarise(Freq=sum(Freq))
sci_type=sci_type[order(sci_type$Freq),]
sci_type$Region=factor(sci_type$Region,levels = unique(sci_type$Region))
sci_type$freq=sci_type$Freq/sum(sci_type$Freq)
sci_type$label=paste(sci_type$Freq,"(",round(sci_type$freq,2)*100,"%)",sep="")

sci_p=ggplot(sci_type,aes(y=Region,x=Freq,fill=Region))+geom_col(alpha=0.8)+
  geom_text(aes(label=label),vjust=0.5,size=3,hjust=-0.05)+
  theme_classic()+
  scale_fill_manual(values = Region_col)+
  theme(axis.text.y = element_text(angle=0,vjust=0.5,hjust=1),
        plot.title = element_text(size = 14, face = 'bold', hjust = 0.5))+
  xlab("No. of ncHLAp")+ylab("")+
  scale_x_continuous(expand =expansion(mult = c(0, 0.27)))+
  ggtitle("Science(517)")
print(sci_p)
```
