---
title: "Fig.S10"
output: html_document
---

### Fig.S10A
```{r,warning=F,message=F,fig.height=8,fig.width=5}
library(viridis)
library(Seurat)
library(ComplexHeatmap)
library(reshape2)
load("data/CD8_tai_5samples_clean_Annotation.Rdata")
geneset1 = rio::import("data/ssGSEA_marker1.xlsx")
geneset1=geneset1[geneset1$gene!="IL17A",]

dotpl=DotPlot(sce, 
              features = geneset1$gene,
              cols = c("lightgrey", "blue"),
              dot.scale = 8,
              group.by = "celltype_Final") + 
  RotatedAxis()

dot_ht=acast(dotpl@data,features.plot~id,value.var = "avg.exp")

gn_type=geneset1[is.element(geneset1$gene,rownames(dot_ht)),]
gn_type$Signature=factor(gn_type$Signature,levels = unique(gn_type$Signature))

dot_ht[dot_ht>3]=3
Heatmap(dot_ht[gn_type$gene,],cluster_columns = F,cluster_rows = F,show_row_dend = F,row_split =factor(gn_type$Signature),
        col=viridis_pal()(12),row_title_rot = 0,border_gp = gpar(col="black"),
        rect_gp = gpar(col="black"),row_names_side = 'left',row_names_gp = gpar(fontsize=8),
        column_names_side = "top",name="Mean Exp",column_names_gp = gpar(fontsize=8),
        row_title_gp = gpar(fontsize=10,fontface="bold"))
```

### Fig.S10B-D
```{r,warning=F,message=F,fig.height=3,fig.width=3.5}
library(Seurat)
library(ggplot2)
load("data/CD8_tai_5samples_clean_Annotation.Rdata")
celltype_col=c("#1F77B4FF","#D62728FF","#2CA02CFF","#7C878EFF","#FF7F0EFF","#8C564BFF","#9467BDFF","#E377C2FF","#6EE2FFFF","#8F7700FF","#5C88DAFF","#84BD00FF","#FFCD00FF")[1:6]
names(celltype_col)=unique(sce$celltype_Final)
#specific
barcode_cdr3=read.csv(paste("data/tai1_filtered_contig_annotations_filteredcontig.csv",sep=""))
cdr3=read.csv(paste("data/tai1_sepcific_ABpair_N_clonetype.csv",sep=""))

cell_cdr3=merge(barcode_cdr3,cdr3)
tai1_specif_cells=cell_cdr3$barcode

tcr=c("TRA:CAEIPNQAGTALIF;TRB:CASSQGTGSYEQYF",
      "TRA:CLGSGGYNKLIF;TRB:CAISESYGRGSSYEQYF",
      "TRA:CAARQIAGGTSYGKLTF;TRB:CSVEERHEQYF")

tai1_tcr=cell_cdr3[is.element(cell_cdr3$cdr3_pair,tcr),]
tai1_tcr=tai1_tcr[is.element(paste("tai1_",tai1_tcr$barcode,sep=""),colnames(sce)),]

sce$tai1_tcr="No"
sce$tai1_tcr[match(paste("tai1_",tai1_tcr$barcode,sep=''),colnames(sce))]=tai1_tcr$cdr3_pair

meta=sce@meta.data
umap_loc=Embeddings(sce,reduction = "umap")
#identical(rownames(meta_Tcell),rownames(umap_loc))
meta=cbind(meta,umap_loc)
meta$Celltype=meta$celltype_Final
meta$Celltype[meta$Celltype=="T_Prol"]="Tpro"
meta_Tcell=meta

seq=tcr
for(i in 1:length(seq)){
  p1=ggplot(data=meta_Tcell,aes(x=umap_1,y=umap_2,col=Celltype))+
    geom_point(size=0.01,col="grey90",data = meta_Tcell[meta_Tcell$tai1_tcr!=seq[i],])+
    geom_point(size=0.5,alpha=0.4,data = meta_Tcell[meta_Tcell$tai1_tcr==seq[i],])+
    scale_color_manual(values =celltype_col)+theme_classic()+
    guides(color=guide_legend(override.aes = list(size=2)))+
    ggtitle(paste("TCR Exp1-",i," \n",sub(";",";\n",seq[i]),"(",sum(meta_Tcell$tai1_tcr==seq[i]),")",sep=""))+
    theme(plot.title = element_text(hjust = 0.5,face="bold"))
  print(p1)
}
```

### Fig.S10E
```{r,warning=F,message=F,fig.height=4,fig.width=4}
library(foreach)
library(reshape2)
library(dplyr)
library(venn)
fl=dir("data/annotation")[-c(2,3)]
dt=foreach(i=1:length(fl)) %do% read.csv(paste("data/annotation/",fl[i],sep=""))
neg_TRA=read.delim("data/annotation/Sample_JZ25214718-1023-01-2025BA44A_14R1_nofilter_4.7_SC.clones_TRA.tsv")
neg_TRB=read.delim("data/annotation/Sample_JZ25214718-1023-01-2025BA44A_14R1_nofilter_4.7_SC.clones_TRB.tsv")

df=list()
for(i in 1:length(fl)){
  stat=dcast(dt[[i]],barcode~chain)
  stat_filter=stat[stat$TRA==1&stat$TRB==1,]
  dt[[i]]=dt[[i]][is.element(dt[[i]]$barcode,stat_filter$barcode),]
  dt[[i]]=dt[[i]][dt[[i]]$chain=="TRA"|dt[[i]]$chain=="TRB",]
  dt[[i]]$cdr3_aa=paste(dt[[i]]$chain,dt[[i]]$cdr3,sep=":")
  
  cell_aa=dt[[i]][order(dt[[i]]$barcode,dt[[i]]$chain),]%>%group_by(barcode)%>%summarise(cdr3_pair=paste0(cdr3_aa,collapse = ";"))
  #write.csv(cell_aa,paste("res/",sub("_contig_annotations.csv","_contig_annotations_filteredcontig.csv",fl[i]),sep=""),row.names = F)
  
  df[[i]]=cell_aa%>%group_by(cdr3_pair)%>%summarise(frequency=length(barcode))
  df[[i]]$proportion=df[[i]]$frequency/sum(df[[i]]$frequency)
  df[[i]]$TRA=gsub("TRA:|;.*","",df[[i]]$cdr3_pair)
  df[[i]]$TRB=gsub(".*TRB:","",df[[i]]$cdr3_pair)
  # write.csv(df[[i]],paste("res/",sub("_contig_annotations.csv","_clonotypes.csv",fl[i]),sep=""),row.names = F)
  df[[i]]=df[[i]][!is.element(df[[i]]$TRA,neg_TRA$aaSeqCDR3),]
  df[[i]]=df[[i]][!is.element(df[[i]]$TRB,neg_TRB$aaSeqCDR3),]
  #write.csv(df[[i]],paste("res/",sub("_contig_annotations.csv","_clonotypes_filter44A.csv",fl[i]),sep=""),row.names = F)
}

#tai1 specific bubble
tai1_spec=setdiff(df[[2]]$cdr3_pair,union(df[[1]]$cdr3_pair,union(df[[3]]$cdr3_pair,df[[4]]$cdr3_pair)))

tai1_dt=df[[2]][is.element(df[[2]]$cdr3_pair,tai1_spec),]
tai1_dt=unique(tai1_dt)

#write.csv(tai1_dt[order(tai1_dt$frequency,decreasing = T),],"res/tail1_sepcific_ABpair_N_clonetype.csv",row.names = F)

#tai2 specific bubble
tai2_spec=setdiff(df[[3]]$cdr3_pair,union(df[[1]]$cdr3_pair,union(df[[2]]$cdr3_pair,df[[4]]$cdr3_pair)))

tai2_dt=df[[3]][is.element(df[[3]]$cdr3_pair,tai2_spec),]
tai2_dt=unique(tai2_dt)

#write.csv(tai2_dt[order(tai2_dt$frequency,decreasing = T),],"res/tail2_sepcific_ABpair_N_clonetype.csv",row.names = F)

#liugan specific bubble
liugan_spec=setdiff(df[[1]]$cdr3_pair,union(df[[2]]$cdr3_pair,union(df[[3]]$cdr3_pair,df[[4]]$cdr3_pair)))

liugan_dt=df[[1]][is.element(df[[1]]$cdr3_pair,liugan_spec),]
liugan_dt=unique(liugan_dt)

#write.csv(liugan_dt[order(liugan_dt$frequency,decreasing = T),],"res/liugan_sepcific_ABpair_N_clonetype.csv",row.names = F)

#wugan specific bubble
wugan_spec=setdiff(df[[4]]$cdr3_pair,union(df[[2]]$cdr3_pair,union(df[[3]]$cdr3_pair,df[[1]]$cdr3_pair)))

wugan_dt=df[[4]][is.element(df[[4]]$cdr3_pair,wugan_spec),]
wugan_dt=unique(wugan_dt)

#write.csv(wugan_dt[order(wugan_dt$frequency,decreasing = T),],"res/wugan_sepcific_ABpair_N_clonetype.csv",row.names = F)

#venn
All=list(GILGFVFTL=na.omit(unique(df[[1]]$cdr3_pair)),
         `Exp1-SSS`=na.omit(unique(df[[2]]$cdr3_pair)),
         `Exp1-STS`=na.omit(unique(df[[3]]$cdr3_pair)),
         Control=na.omit(unique(df[[4]]$cdr3_pair)))

venn(All,zcolor=c("#009E73","#E6F598","#56B4E9","#C2A5CF"),ilabels = "counts",box=F,
     col=c("#009E73","#E6F598","#56B4E9","#C2A5CF"),ilcs=0.8,opacity = 0.7)
```
