---
title: "Fig3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data

```{r,eval=F}
library(openxlsx)
#This data is generated by code TableS4/TableS4.html
df=read.xlsx("data/AllSample_Peptide_ASPC1_allAnnotated_MS_HLApcheck.xlsx")

pre_filt=which(grepl("MS", colnames(df)) & !grepl("MS_HLAp", colnames(df)))[-1]
post_filt=grep("MS_HLAp_",colnames(df))[-1]
  
stat=list()
#All peptide
stat[[1]]=colSums(df[rowSums(df[,pre_filt])>0,pre_filt],na.rm=T)

#MHC binding
stat[[2]]=colSums(df[df$`HLAbinding-annotated`==1,post_filt],na.rm=T)
#ribo-seq filter
stat[[3]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE,post_filt],na.rm=T)
#MS-benign filter
stat[[4]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE,post_filt],na.rm=T)
#BN
stat[[5]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="BN",post_filt],na.rm=T)
#NCBI_Uniport
stat[[6]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="NCBI_Uniport",post_filt],na.rm=T)
#Mutation
stat[[7]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Mutation",post_filt],na.rm=T)
#Fusion
stat[[8]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Fusion",post_filt],na.rm=T)
#IR
stat[[9]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="IR",post_filt],na.rm=T)
#TElocal
stat[[10]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="TElocal",post_filt],na.rm=T)
#TEprof2
stat[[11]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="TEprof2",post_filt],na.rm=T)
#DN
stat[[12]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="DN",post_filt],na.rm=T)
#Cis
stat[[13]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Cis",post_filt],na.rm=T)
#Trans
stat[[14]]=colSums(df[df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Trans",post_filt],na.rm=T)


item_label=c("MS-All","MHC-binding","Ribo-benign filter","MS-benign filter",
             "BN","Uniport","Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")
item_N=c(sum(rowSums(df[,pre_filt])>0),sum(df$`HLAbinding-annotated`==1),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="BN"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="NCBI_Uniport"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Mutation"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Fusion"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="IR"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="TElocal"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="TEprof2"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="DN"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Cis"),
         sum(df$`HLAbinding-annotated`==1&df$ribo_Integrate==FALSE&df$hh_Integrate==FALSE&df$thymus_Integrate==FALSE&df$`source-annotated`=="Trans"))
item=paste(item_label,"(",format(item_N,big.mark = ",", scientific = FALSE, trim = TRUE),")",sep="")
save(stat,item,file="Fig3_stat.Rdata")

stat_dt=do.call(rbind,stat)
rownames(stat_dt)=item_label
write.xlsx(stat_dt,"Fig3_data.xlsx",rowNames=T)
```

## plot

```{r,fig.height=11,fig.width=11}
library(openxlsx)
library(ggplot2)
library(cowplot)
load("Fig3_stat.Rdata")
ylim_list=list(c(0,55000),c(0,42000),c(0,40000),c(0,40000),c(0,20000),
               c(0,15000),c(0,6),c(0,1.2),c(0,28),c(0,39),c(0,7),c(0,310),c(0,1.2),c(0,20))
break_list=list(c(0,20000,40000),c(0,20000,40000),c(0,20000,40000),c(0,20000,40000),
                c(0,10000,20000),c(0,6000,12000),c(0,3,6),c(0,1),
                c(0,10,20),c(0,15,30),c(0,3,6),c(0,150,300),c(0,1),c(0,10,20))

my_theme=theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5,size = 10),strip.background = element_blank(),
               panel.grid = element_blank(),strip.text = element_blank(),
               panel.background = element_rect(colour = "black",fill=NA))


col=c("#445d80","#445d80",rep("#1F78B4",3),rep("#A6CEE3",9))

fig=list()
for(i in 1:14){
  stat_tab=as.data.frame(stat[[i]])
  rownames(stat_tab)=sub("MS_HLAp_|MS_","",rownames(stat_tab))
   stat_tab=as.data.frame(stat_tab)
  colnames(stat_tab)[1]="value"
  stat_tab$Var1=factor(rownames(stat_tab),levels=rownames(stat_tab)[c(1:10,12,11,16,14,13,15,41:43,17:40,44:46)])
  
  if(i==1){
    fig[[i]]=ggplot(stat_tab,aes(x=Var1,y=value))+geom_col(fill=col[i])+
      my_theme+theme(axis.ticks.x = element_blank(),axis.text.x= element_blank())+xlab("")+
      ylab(item[i])+geom_text(aes(label = value),size=1.5,vjust=-0.5)+
      scale_y_continuous(breaks = break_list[[i]],limits = ylim_list[[i]])+
      theme(plot.margin = unit(c(0.2,1,0,1),"cm"),axis.title.y = element_text(angle=0),legend.position = "none")
    
  }else if(i==length(stat)){
    fig[[i]]=ggplot(stat_tab,aes(x=Var1,y=value))+geom_col(fill=col[i])+
      my_theme+xlab("")+
      ylab(item[i])+geom_text(aes(label = value),size=1.5,vjust=-0.5)+
      scale_y_continuous(breaks = break_list[[i]],limits = ylim_list[[i]])+
      theme(plot.margin = unit(c(0,1,0,1),"cm"),axis.title.y = element_text(angle=0))
  }else{
    fig[[i]]=ggplot(stat_tab,aes(x=Var1,y=value))+geom_col(fill=col[i])+
      my_theme+theme(axis.ticks.x = element_blank(),axis.text.x= element_blank())+xlab("")+
      ylab(item[i])+geom_text(aes(label = value),size=1.5,vjust=-0.5)+
      scale_y_continuous(breaks = break_list[[i]],limits = ylim_list[[i]])+
      theme(plot.margin = unit(c(0,1,0,1),"cm"),axis.title.y = element_text(angle=0),legend.position = "none")
  }
}

col_p3=plot_grid(plotlist=fig,ncol=1,align = "v",rel_heights = c(rep(1,13),2.2))

#pdf("Fig3.pdf",height = 11,width = 11)
print(col_p3)
#dev.off()
```