---
title: "TableS4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data

```{r,eval=F}
library(dplyr)
library(foreach)
library(ggpubr)
library(reshape2)
library(cowplot)
library(openxlsx)

#merge MSdata of 4 diseases
dt1=read.delim("data/Prostate_MSdata_Annotation_final_S16.xls",sep="\t",check.names = F,stringsAsFactors = F,header = T)
dt1$Prostate_N=rowSums(dt1[,grep("MS",colnames(dt1))])
rep_pep=names(table(dt1$Peptide)[table(dt1$Peptide)>1])
for(i in 1:length(rep_pep)){
  gl=which(dt1$Peptide==rep_pep[i])
  del_gl=which(dt1$`source-annotated`[gl]=="Trans")
  dt1=dt1[-gl[del_gl],]
}

dt2=read.delim("data/DAC_MSdata_Annotation_final.xls",sep="\t",check.names = F,stringsAsFactors = F,header = T)
dt2$DAC_N=rowSums(dt2[,grep("MS",colnames(dt2))])

dt3=read.delim("data/PDX_MSdata_Annotation_final.xls",sep="\t",check.names = F,stringsAsFactors = F,header = T)
dt3$PDX_N=rowSums(dt3[,grep("MS",colnames(dt3))])
rep_pep=names(table(dt3$Peptide)[table(dt3$Peptide)>1])
for(i in 1:length(rep_pep)){
  gl=which(dt3$Peptide==rep_pep[i])
  del_gl=which(dt3$`source-annotated`[gl]=="Trans")
  dt3=dt3[-gl[del_gl],]
}

dt4=read.delim("data/BJM_MSdata_Annotation_final.xls",sep="\t",check.names = F,stringsAsFactors = F,header = T)
dt4$BJM_N=rowSums(dt4[,grep("MS",colnames(dt4))])
rep_pep=names(table(dt4$Peptide)[table(dt4$Peptide)>1])
for(i in 1:length(rep_pep)){
  gl=which(dt4$Peptide==rep_pep[i])
  del_gl=which(dt4$`source-annotated`[gl]=="Unannotated")
  dt4=dt4[-gl[del_gl],]
}

dt5=read.delim("data/TCC_MSdata_Annotation_final.xls",sep="\t",check.names = F,stringsAsFactors = F,header = T)
dt5$TCC_N=rowSums(dt5[,grep("MS",colnames(dt5))])

#label "HLAbinding" and "source" diseases or patients for discriminating
colnames(dt1)[c(19,25)]=paste(colnames(dt1)[c(19,25)],"Prostate",sep="_")
colnames(dt2)[c(14,26)]=paste(colnames(dt2)[c(14,26)],"DAC",sep="_")
colnames(dt3)[c(16,30)]=paste(colnames(dt3)[c(16,30)],"PDX",sep="_")
colnames(dt4)[c(6,10)]=paste(colnames(dt4)[c(6,10)],"PCA-06",sep="_")
colnames(dt5)[c(6,10)]=paste(colnames(dt5)[c(6,10)],"TCC",sep="_")

#merge all data
dt=merge(dt1,dt2,all=T)
dt=merge(dt,dt3,all=T)
dt=merge(dt,dt4,all=T)
dt=merge(dt,dt5,all=T)

#revise HLAbinding-annotated NA
dt$`HLAbinding-annotated_Prostate`[is.na(dt$`HLAbinding-annotated_Prostate`)]=0
dt$`HLAbinding-annotated_DAC`[is.na(dt$`HLAbinding-annotated_DAC`)]=0
dt$`HLAbinding-annotated_PDX`[is.na(dt$`HLAbinding-annotated_PDX`)]=0
dt$`HLAbinding-annotated_PCA-06`[is.na(dt$`HLAbinding-annotated_PCA-06`)]=0
dt$`HLAbinding-annotated_TCC`[is.na(dt$`HLAbinding-annotated_TCC`)]=0

#revise MS NA
sub_dt=dt[,grep("MS",colnames(dt))]
sub_dt[is.na(sub_dt)]=0
dt[,grep("MS",colnames(dt))]=sub_dt

#revise grep NA
sub_dt=dt[,grep("_N",colnames(dt))]
sub_dt[is.na(sub_dt)]=0
dt[,grep("_N",colnames(dt))]=sub_dt

#merge the number of prostate and BJM
dt$Prostate_N=dt$Prostate_N+dt$BJM_N
dt=dt[,-which(colnames(dt)=="BJM_N")]

dt$`HLAbinding-annotated`=rowSums(dt[,c("HLAbinding-annotated_Prostate",
                                        "HLAbinding-annotated_PDX",
                                        "HLAbinding-annotated_DAC",
                                        "HLAbinding-annotated_PCA-06",
                                        "HLAbinding-annotated_TCC")])
dt$`HLAbinding-annotated`[dt$`HLAbinding-annotated`>0]=1

dt$`source-annotated`=foreach(i=1:nrow(dt),.combine=c) %do% paste0(na.omit(unique(as.character(dt[i,c("source-annotated_Prostate","source-annotated_PCA-06","source-annotated_DAC","source-annotated_PDX","source-annotated_TCC")]))),collapse = ";")
dt$`source-annotated`=sub(";Unannotated|Unannotated;","",dt$`source-annotated`)

#revise source
sub1=dt[grep("IR;|;IR",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]
dt[grep("IR;|;IR",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]=foreach(i=1:nrow(sub1),.combine = rbind) %do% sub("TElocal|DN|TEprof2","Unannotated",sub1[i,])
sub2=dt[grep("IR;|;IR",dt$`source-annotated`),grep("grep",colnames(dt))]
dt[grep("IR;|;IR",dt$`source-annotated`),grep("grep",colnames(dt))]=foreach(i=1:nrow(sub2),.combine = rbind) %do% sub("DN-.*|TElocal-.*|TEprof2-.*",NA,sub2[i,])
dt[grep("IR;|;IR",dt$`source-annotated`),"source-annotated"]="IR"

sub1=dt[grep("TElocal;|;TElocal",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]
dt[grep("TElocal;|;TElocal",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]=foreach(i=1:nrow(sub1),.combine = rbind) %do% sub("DN|TEprof2","Unannotated",sub1[i,])
sub2=dt[grep("TElocal;|;TElocal",dt$`source-annotated`),grep("grep",colnames(dt))]
dt[grep("TElocal;|;TElocal",dt$`source-annotated`),grep("grep",colnames(dt))]=foreach(i=1:nrow(sub2),.combine = rbind) %do% sub("DN-.*|TEprof2-.*",NA,sub2[i,])
dt[grep("TElocal;|;TElocal",dt$`source-annotated`),"source-annotated"]="TElocal"

sub1=dt[grep("TEprof2;|;TEprof2",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]
dt[grep("TEprof2;|;TEprof2",dt$`source-annotated`),grep("source-annotated_",colnames(dt))]=foreach(i=1:nrow(sub1),.combine = rbind) %do% sub("DN","Unannotated",sub1[i,])
sub2=dt[grep("TEprof2;|;TEprof2",dt$`source-annotated`),grep("grep",colnames(dt))]
dt[grep("TEprof2;|;TEprof2",dt$`source-annotated`),grep("grep",colnames(dt))]=foreach(i=1:nrow(sub2),.combine = rbind) %do% sub("DN-.*",NA,sub2[i,])
dt[grep("TEprof2;|;TEprof2",dt$`source-annotated`),"source-annotated"]="TEprof2"

dt$Gene=foreach(i=1:nrow(dt),.combine = c) %do% paste0(unique(na.omit(as.character(dt[i,grep("grep",colnames(dt))]))),collapse = ";")
dt$Gene=sub("^;","",dt$Gene)

#Standardized location
Loci=foreach(i=1:nrow(dt)) %do% gsub("\\[[^]]*\\]","",gsub("\\([^)]*\\)","",unique(na.omit(as.character(dt[i,grep("grep",colnames(dt))])))))

dt$Loci=foreach(i=1:nrow(dt),.combine=c) %do% paste0(unique(Loci[[i]][Loci[[i]]!=""]),collapse =";" )
gl=grep("Multimapping",dt$Gene)
dt$Multimapping=FALSE
dt$Multimapping[gl]=TRUE
gl1=setdiff(setdiff(grep(";",dt$Loci),grep("BN",dt$`source-annotated`)),gl)
dt$Multimapping[gl1[grep('chr',dt$Loci[gl1])]]=TRUE

#################################add ASPC1
dt_ASPC1=read.delim("data/AsPC1_AllPeptide_MS_source_HLA_V4.xls",sep="\t",header = T,stringsAsFactors = F,check.names = F)
dt_ASPC1_mhc=melt(dt_ASPC1[,c(1,7:10)],id.vars = "Peptide")
dt_ASPC1_mhc=dt_ASPC1_mhc[dt_ASPC1_mhc$value!="",]
dt_ASPC1_mhc$variable=paste(dt_ASPC1_mhc$variable,"(",dt_ASPC1_mhc$value,")",sep="")
dt_ASPC1_mhc_dt=dt_ASPC1_mhc%>%group_by(Peptide)%>%summarise(MHC_binding_ASPC1=paste0(unique(variable),collapse = ";"))
dt_ASPC1=merge(dt_ASPC1,dt_ASPC1_mhc_dt,by="Peptide",all.x = T)
dt_ASPC1=dt_ASPC1[,-c(7:10)]
colnames(dt_ASPC1)[c(4,6)]=paste(colnames(dt_ASPC1)[c(4,6)],"ASPC1",sep="_")

dt_merge=merge(dt_ASPC1,dt,all=T)
colnames(dt_merge)[3]="MS_ASPC1"
sub1=dt_merge[,grep("MS_",colnames(dt_merge))]
sub1[is.na(sub1)]=0
dt_merge[,grep("MS_",colnames(dt_merge))]=sub1

dt_merge$`HLAbinding-annotated`[is.na(dt_merge$`HLAbinding-annotated`)]=0

#add other annotation
cedar=read.table("data/HLA_database/NeoAtlas/CEDAR_filter_20250116.tsv",sep="\t",header = T)
colnames(cedar)[2]="HLA_allele"

hlathena=read.table("data/HLA_database/NeoAtlas/HLAthena_data.xls",sep="\t",header = T)

iedb=read.table("data/HLA_database/NeoAtlas/IEDB_filter_20250116.tsv",sep="\t",header = T)
colnames(iedb)[2]="HLA_allele"

pep1=read.xlsx("data/HLA_database/NeoAtlas/HLA_trans_annotation_noAA_20250311.xlsx")
pep2=read.xlsx("data/HLA_database/NeoAtlas/HLA-C 重新注释的蛋白质cis_250311.xlsx")
pep1$Peptide[grep("\\(\\+",pep1$Peptide)]=gsub("\\(\\+[0-9]*\\.[0-9]*\\)","",pep1$Peptide[grep("\\(\\+",pep1$Peptide)])

NeoAtlas=data.frame(Peptide=unique(c(cedar$Peptide,hlathena$sequence,iedb$Peptide,
                                     pep1$Peptide,pep2$Peptide)))
NeoAtlas$CEDAR=ifelse(is.element(NeoAtlas$Peptide,cedar$Peptide),TRUE,FALSE)
NeoAtlas$IEDB=ifelse(is.element(NeoAtlas$Peptide,iedb$Peptide),TRUE,FALSE)
NeoAtlas$HLAthena=ifelse(is.element(NeoAtlas$Peptide,hlathena$sequence),TRUE,FALSE)
NeoAtlas$Protein=ifelse(is.element(NeoAtlas$Peptide,union(pep1$Peptide,pep2$Peptide)),TRUE,FALSE)

#map CEDAR,HLAthena,IEDB,Protein by peptide
dt_NeoAtlas=merge(dt_merge,NeoAtlas,by="Peptide",all.x = T)

rna=read.xlsx("data/HLA_database/NeoAtlas/NeoAtlas_RNA_250319_V2.xlsx")
dt_NeoAtlas$RNA=is.element(dt_NeoAtlas$Peptide,rna$Peptide)

#add science annotation
science=read.xlsx("data/HLA_database/science.adk3487_tables_s1_to_s14 2.xlsx",sheet = "ST6_ncHLAp PDAC PDO  ",startRow = 2)
#只用peptide
sub_sci=unique(science[,c("seq_upper","hh_ip_detection","ribo_detection","thymus_ip_detection","cancer_restricted")])
colnames(sub_sci)[1]="Peptide"
dat=merge(dt_NeoAtlas,sub_sci,all.x = T)

#add HLA_2020_12 annotation. Map by peptide
dt=read.table("data/hla_2020.12/hla_2020.12/HLA_peptides.tsv",sep="\t",header = T,stringsAsFactors = F)
sub_hla=data.frame(Peptide=unique(dt$peptide_sequence),HLA2020=TRUE)
dt_NeoAtlas_RNA_sci_hla2020=merge(dat,sub_hla,by="Peptide",all.x=T)

#hh annotation
dt=dt_NeoAtlas_RNA_sci_hla2020
hh=read.table("data/HLA_database/Normal_Sample_MS/all_combined_peptides.txt",sep="\t",header = T,stringsAsFactors = F)
thymus=read.table("data/HLA_database/thymus/combined_peptides.txt",sep="\t",header = T,stringsAsFactors = F)

dt$hh=is.element(dt$Peptide,unique(hh$Peptide))
dt$thymus=is.element(dt$Peptide,unique(thymus$Peptide))

#add ribo annotation
item=c("brain","fat","fibroblast","haec","hcaec","hepatocytes",'kidney',"vsmc")
df=foreach(i=1:length(item)) %do% read.table(paste("data/riboseq_filter_peptide_merge/",item[i],".RiboTishPrediction_peptide.txt",sep=""),
                                             sep="\t",stringsAsFactors = F,header=F)

ribo_dt=do.call(rbind,df)
ribo_dt$Peptide=foreach(i=1:nrow(ribo_dt),.combine=c) %do% unlist(strsplit(ribo_dt$V1[i],split="_"))[2]

dt$ribo_seq=is.element(dt$Peptide,unique(ribo_dt$Peptide))

#Integrate science and we detected
dt$ribo_Integrate=ifelse(dt$ribo_detection==TRUE|dt$ribo_seq==TRUE,TRUE,FALSE)
dt$hh_Integrate=ifelse(dt$hh_ip_detection==TRUE|dt$hh==TRUE,TRUE,FALSE)
dt$thymus_Integrate=ifelse(dt$thymus_ip_detection==TRUE|dt$thymus==TRUE,TRUE,FALSE)
dt$ribo_Integrate[is.na(dt$ribo_Integrate)]=FALSE
dt$hh_Integrate[is.na(dt$hh_Integrate)]=FALSE
dt$thymus_Integrate[is.na(dt$thymus_Integrate)]=FALSE

dt_merge_pep=dt
sub1=dt_merge_pep[,grep("HLAbinding-annotated",colnames(dt_merge_pep))]
sub1[is.na(sub1)]=0
dt_merge_pep[,grep("HLAbinding-annotated",colnames(dt_merge_pep))]=sub1

#################add Elispot annotation############################################################
dat=dt_merge_pep
#Elispot
Elispot_2=read.xlsx("data/Supplementary Table3 Immunogenicity assessment of HLAp(2).xlsx",startRow = 2)
Elispot_2$Elispot_ID=paste(Elispot_2$Peptide,sub("Exp","E",Elispot_2$Experiment.Code),sep=":")
Elispot_2$Elispot_ID=sub(":NA","",Elispot_2$Elispot_ID)
Elispot_2$Imm=substr(Elispot_2$Immunogenic,1,3)
Elispot_2$Imm_ID=ifelse(Elispot_2$Imm=="neg","-","+")
Elispot_2$Elispot_id=paste(Elispot_2$Elispot_ID,"(",Elispot_2$Imm_ID,")",sep="")
Elispot_df=Elispot_2%>%group_by(Peptide.Sequence)%>%summarise(Elispot_ID=paste0(Elispot_id,collapse = ";"))
colnames(Elispot_df)[1]="Peptide"
dat$ELISPOT=ifelse(is.element(dat$Peptide,Elispot_df$Peptide),1,0)

dat=merge(dat,Elispot_df,by=c("Peptide"),all.x=T)

##peptide verify
fl1=dir("data/验证肽/肽质谱验证/ASPC1 肽验证")
fl2=dir("data/验证肽/肽质谱验证/G517_SVGPDF")
fl3=dir("data/验证肽/肽质谱验证/W_G630_PDF")

fl1=unique(sub(".svg.*","",sub("^[^.]*_","",fl1)))
fl2=unique(sub(".svg.*","",sub("^[^.]*_","",fl2)))
fl3=unique(sub(".svg.*","",sub("^[^.]*\\.","",fl3)))

pep_prof=data.frame(dataset=c(rep("ASPC1 肽验证",length(fl1)),rep("G517_SVGPDF",length(fl2)),rep("W_G630_PDF",length(fl3))),
                    Peptide=c(fl1,fl2,fl3))
pep_prof_df=dcast(pep_prof,Peptide~dataset,fun.aggregate = length)
pep_prof_df$ASPC1_G517_WG630=rowSums(pep_prof_df[,2:4])
dat=merge(dat,pep_prof_df[,c(1,5)],all.x=T)

#define publicpaper 
dt1=read.xlsx("data/Table S6.xlsx",sheet = "all_fusion")
dt2=read.xlsx("data/Table S6.xlsx",sheet = "all_splicing")
dt3=read.xlsx("data/Table S6.xlsx",sheet = "frequent_orf_antigens",startRow = 2)
colnames(dt3)[1:2]=c("pep","typ")
dt3$typ="orf"
dt5=read.xlsx("data/Table S7.xlsx",sheet = "all_ir")
dt6=read.xlsx("data/Table S9.xlsx",sheet = "ts_te_antigen")

tab_dt=unique(rbind(dt1[,2:3],dt2[,2:3],dt3[,1:2],dt5[,2:3],dt6[,2:3]))
tab_dt=dcast(tab_dt,pep~typ)
dat=merge(dat,tab_dt,by.x = "Peptide",by.y="pep",all.x = T)
dat$PublicPaper=rowSums(!is.na(dat[,c("ERV","fusion","intron_retention","orf","splicing" )]))

#add scinece 2025
dt7=read.xlsx("data/2025-Science-Neoantigen_.xlsx",sheet = "ST5")
dt8=read.xlsx("data/HLA_database/science.adk3487_tables_s1_to_s14 2.xlsx",sheet = "ST6_ncHLAp PDAC PDO  ",startRow = 2)
dt9=read.xlsx("data/HLA_database/science.adk3487_tables_s1_to_s14 2.xlsx",sheet = "ST7_ncHLAp PDAC bulk tumors",startRow = 2)
colnames(dt9)[1]="org_line"
dt7_9=rbind(dt7,dt8[,c("org_line","seq_upper")],dt9[,c("org_line","seq_upper")])
dt7_tab=dcast(dt7_9,seq_upper~org_line)
dat=merge(dat,dt7_tab,by.x = "Peptide",by.y = "seq_upper",all.x = T)
dat$Science_2025=rowSums(!is.na(dat[,colnames(dt7_tab)[-1]])&dat[,colnames(dt7_tab)[-1]]!=0)
dat$Science_2025[dat$Science_2025!=0]=1
dat$SCI=rowSums(!is.na(dat[,colnames(dt7_tab)[-1]])&dat[,colnames(dt7_tab)[-1]]!=0)

###################################add RNA_fish annoattion
rna_fish=read.xlsx("data/laolin-NIEA-MGA-MLN-expression.xlsx",sheet = "RNA-FISH tumor")
dat$RNA_fish=ifelse(is.element(dat$Peptide,rna_fish$Peptide),"Yes","No")
write.xlsx(dat,"res/AllSamples_ASPC1_allAnnotated.xlsx")

#check HLA binding MSdata
#add columns of MS_HLAp_*
dt=dat
dt_HLAp=dt[,grep("MS",colnames(dt))]
colnames(dt_HLAp)=sub("MS_","MS_HLAp_",colnames(dt_HLAp))
dt_HLAp_grep=dt[,grep("grep",colnames(dt))]
colnames(dt_HLAp_grep)=sub("grep_","grep_HLAp_",colnames(dt_HLAp_grep))
dt=cbind(dt,dt_HLAp)
dt=cbind(dt,dt_HLAp_grep)

#revise PCA-01
dt$`MHC_binding_PCA-01`[dt$`MHC_binding_PCA-01`==""&!is.na(dt$`MHC_binding_PCA-01`)]=NA
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-01`)&rowSums(dt[,grep("MS_PCA-01-",colnames(dt))])>0)
ms_col=grep("MS_HLAp_PCA-01-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-01-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#revise PCA-02
if(sum(dt$`MHC_binding_PCA-02`==""&!is.na(dt$`MHC_binding_PCA-02`))>0){
  dt$`MHC_binding_PCA-02`[dt$`MHC_binding_PCA-02`==""&!is.na(dt$`MHC_binding_PCA-02`)]=NA
}
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-02`)&dt[,grep("MS_PCA-02-",colnames(dt))]>0)
ms_col=grep("MS_HLAp_PCA-02-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-02-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#revise PCA-03
if(sum(dt$`MHC_binding_PCA-03`==""&!is.na(dt$`MHC_binding_PCA-03`))>0){
  dt$`MHC_binding_PCA-03`[dt$`MHC_binding_PCA-03`==""&!is.na(dt$`MHC_binding_PCA-03`)]=NA
}
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-03`)&dt[,grep("MS_PCA-03-",colnames(dt))]>0)
ms_col=grep("MS_HLAp_PCA-03-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-03-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#revise PCA-04
if(sum(dt$`MHC_binding_PCA-04`==""&!is.na(dt$`MHC_binding_PCA-04`))>0){
  dt$`MHC_binding_PCA-04`[dt$`MHC_binding_PCA-04`==""&!is.na(dt$`MHC_binding_PCA-04`)]=NA
}
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-04`)&rowSums(dt[,grep("MS_PCA-04-",colnames(dt))])>0)
ms_col=grep("MS_HLAp_PCA-04-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-04-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#revise PCA-05
if(sum(dt$`MHC_binding_PCA-05`==""&!is.na(dt$`MHC_binding_PCA-05`))>0){
  dt$`MHC_binding_PCA-05`[dt$`MHC_binding_PCA-05`==""&!is.na(dt$`MHC_binding_PCA-05`)]=NA
}
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-05`)&rowSums(dt[,grep("MS_PCA-05-",colnames(dt))])>0)
ms_col=grep("MS_HLAp_PCA-05-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-05-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#revise PCA-06
if(sum(dt$`MHC_binding_PCA-06`==""&!is.na(dt$`MHC_binding_PCA-06`))>0){
  dt$`MHC_binding_PCA-06`[dt$`MHC_binding_PCA-06`==""&!is.na(dt$`MHC_binding_PCA-06`)]=NA
}
#revise rows
gl=which(is.na(dt$`MHC_binding_PCA-06`)&rowSums(dt[,grep("MS_PCA-06-",colnames(dt))])>0)
ms_col=grep("MS_HLAp_PCA-06-",colnames(dt))
grep_col=grep("grep_HLAp_PCA-06-",colnames(dt))
#revise MS
sub_dt=dt[gl,ms_col]
sub_dt[sub_dt!=0]=0
dt[gl,ms_col]=sub_dt
#revise grep
sub_dt=dt[gl,grep_col]
sub_dt[!is.na(sub_dt)]=NA
sub_dt[sub_dt=='']=NA
dt[gl,grep_col]=sub_dt

#DAC
dac_sp=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4",
         "DAC5","DAC50","DAC53","DAC57","DAC69")
for(i in 1:11){
  gl=which(dt[,paste0("MHC_binding_",dac_sp[i])]==""&!is.na(dt[,paste0("MHC_binding_",dac_sp[i])]))
  if(length(gl)>0){
    dt[gl,paste0("MHC_binding_",dac_sp[i])]=NA
  }
  #revise MS
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",dac_sp[i])])&dt[,paste0("MS_",dac_sp[i])]>0,paste0("MS_HLAp_",dac_sp[i])]
  sub_dt[sub_dt!=0]=0
  dt[is.na(dt[,paste0("MHC_binding_",dac_sp[i])])&dt[,paste0("MS_",dac_sp[i])]>0,paste0("MS_HLAp_",dac_sp[i])]=sub_dt
  #revise grep
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",dac_sp[i])])&dt[,paste0("MS_",dac_sp[i])]>0,paste0("grep_HLAp_",dac_sp[i])]
  sub_dt[!is.na(sub_dt)]=NA
  sub_dt[sub_dt=='']=NA
  dt[is.na(dt[,paste0("MHC_binding_",dac_sp[i])])&dt[,paste0("MS_",dac_sp[i])]>0,paste0("grep_HLAp_",dac_sp[i])]=sub_dt
}

#PDX
pdx_sp=c( "CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
          "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080","CH-17-0087",
          "CH-17-0091")
for(i in 1:13){
  gl=which(dt[,paste0("MHC_binding_",pdx_sp[i])]==""&!is.na(dt[,paste0("MHC_binding_",pdx_sp[i])]))
  if(length(gl)>0){
    dt[gl,paste0("MHC_binding_",pdx_sp[i])]=NA
  }
  #revise MS
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",pdx_sp[i])])&dt[,paste0("MS_",pdx_sp[i])]>0,paste0("MS_HLAp_",pdx_sp[i])]
  sub_dt[sub_dt!=0]=0
  dt[is.na(dt[,paste0("MHC_binding_",pdx_sp[i])])&dt[,paste0("MS_",pdx_sp[i])]>0,paste0("MS_HLAp_",pdx_sp[i])]=sub_dt
  #revise grep
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",pdx_sp[i])])&dt[,paste0("MS_",pdx_sp[i])]>0,paste0("grep_HLAp_",pdx_sp[i])]
  sub_dt[!is.na(sub_dt)]=NA
  sub_dt[sub_dt=='']=NA
  dt[is.na(dt[,paste0("MHC_binding_",pdx_sp[i])])&dt[,paste0("MS_",pdx_sp[i])]>0,paste0("grep_HLAp_",pdx_sp[i])]=sub_dt
}

#TCC
gwa_sp=c( "TCC-01","TCC-02","TCC-03")
for(i in 1:3){
  gl=which(dt[,paste0("MHC_binding_",gwa_sp[i])]==""&!is.na(dt[,paste0("MHC_binding_",gwa_sp[i])]))
  if(length(gl)>0){
    dt[gl,paste0("MHC_binding_",gwa_sp[i])]=NA
  }
  #revise MS
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",gwa_sp[i])])&dt[,paste0("MS_",gwa_sp[i])]>0,paste0("MS_HLAp_",gwa_sp[i])]
  sub_dt[sub_dt!=0]=0
  dt[is.na(dt[,paste0("MHC_binding_",gwa_sp[i])])&dt[,paste0("MS_",gwa_sp[i])]>0,paste0("MS_HLAp_",gwa_sp[i])]=sub_dt
  #revise grep
  sub_dt=dt[is.na(dt[,paste0("MHC_binding_",gwa_sp[i])])&dt[,paste0("MS_",gwa_sp[i])]>0,paste0("grep_HLAp_",gwa_sp[i])]
  sub_dt[!is.na(sub_dt)]=NA
  sub_dt[sub_dt=='']=NA
  dt[is.na(dt[,paste0("MHC_binding_",gwa_sp[i])])&dt[,paste0("MS_",gwa_sp[i])]>0,paste0("grep_HLAp_",gwa_sp[i])]=sub_dt
}

#save this table for Fig.3
write.xlsx(dt,"res/AllSample_Peptide_ASPC1_allAnnotated_MS_HLApcheck.xlsx")

#save this table for TableS4
gl1=grep("MS_|grep_",colnames(dt))
gl2=grep("MS_HLAp|grep_HLAp",colnames(dt))
gl=setdiff(gl1,gl2)
dt_keep=dt[,-gl]
colnames(dt_keep)=sub("HLAp_","",colnames(dt_keep))
write.xlsx(dt_keep[,c(1,2,111:ncol(dt_keep),3:110)],"res/TableS4.xlsx")

#save this table for the following analysis
c_nc=dt_keep[dt_keep$`HLAbinding-annotated`==1&dt_keep$ribo_Integrate==FALSE&dt_keep$hh_Integrate==FALSE&dt_keep$thymus_Integrate==FALSE,]
c_nc=c_nc[c_nc$`source-annotated`!="Unannotated"&c_nc$`source-annotated`!="NCBI_Uniport"&c_nc$`source-annotated`!="BN",]
write.xlsx(c_nc,"res/AllSample_Peptide_Canonical_NonCanonical_MsHLAp.xlsx")
```

