---
title: "Fig.2"
output: html_document
---

### fig.2A
```{r,warning=F,message=F}
library(maftools)
library(openxlsx)
library(ggplot2)
library(reshape2)
library(gridExtra)
library(grid)
library(ggpubr)
library(cowplot)
library(patchwork)
maf=read.maf("data/TableS3_AllSample_Mutation_addPeptide.maf")
#vc_nonSyn = c("Frame_Shift_Del","Frame_Shift_Ins","In_Frame_Del","In_Frame_Ins","Missense_Mutation"))
mt_pep=read.xlsx("data/FigS3_data.xlsx",rowNames=T)

nonsys_mt=maf@variants.per.sample
nonsys_mt$Tumor_Sample_Barcode=as.factor(nonsys_mt$Tumor_Sample_Barcode)

pep_mt=mt_pep["Mutation",]
colnames(pep_mt)=sub("MS_","",colnames(pep_mt))
pep_mt=as.data.frame(t(pep_mt))
pep_mt$nonsys=as.numeric(as.matrix(nonsys_mt[match(rownames(pep_mt),nonsys_mt$Tumor_Sample_Barcode),"Variants"]))
pep_mt$nonsys[is.na(pep_mt$nonsys)]=0

pep_mt$Disease=c(rep("PCa",16),rep("DAC",11),rep("PDX",13),rep("PCa",3),rep("TCC",3))
pep_mt$Type=c("Primary",rep("metastasis",7),rep("Primary",2),"metastasis",
              "Primary",rep("metastasis",3),"Primary",rep("Primary",25),
              rep("metastasis",2),rep("Primary",3))
pep_mt$Sample=gsub("MS_|\\-PST","",rownames(pep_mt))

df=pep_mt[pep_mt$Disease=="PCa"&pep_mt$Type=="Primary",]
df$Sample=factor(df$Sample,levels = rev(df$Sample))

#PCa
{
  # ========== left: NSMs ==========
  p_left <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = nonsys),fill="grey80", stat = 'identity', color = 'grey80', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = nonsys + max(nonsys)*0.02, label =nonsys), 
              hjust = 1, size = 2.5) +
    scale_x_reverse(expand = expansion(mult = c(0.15, 0.0))) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'Number of NSMs', x = NULL, y = NULL) +
    theme_minimal()  +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.y = element_blank(),
      axis.text.x = element_text(size = 9),
      axis.ticks.x = element_line(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 0, 5, 5)
    )+geom_vline(xintercept = -70,linewidth=1)
  
  # ========== right: Mutations ==========
  p_right <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = Mutation), stat = 'identity',fill='#7fb3d5',
             color = '#7fb3d5', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = Mutation + 0.1, label =  Mutation), 
              hjust = 0, size = 2.5, fontface = 'bold') +
    scale_x_continuous(expand = expansion(mult = c(0, 0.2))) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'HLAps mutation-drived', x = NULL, y = NULL) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 9),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x = element_line(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 5, 5, 0)
    )
  
  p1=plot_grid(p_left,p_right)+plot_annotation(title = "PCa Primary (n=6)")&  theme(plot.title = element_text(hjust = 0.5,face = "bold"))
}

#DAC
df=pep_mt[pep_mt$Disease=="DAC",]
df$Sample=factor(df$Sample,levels = rev(df$Sample))
df["DAC73","Mutation"]=0
{
  #df$nonsys=log10(df$nonsys+1)
  # ========== left: NSMs ==========
  p_left <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = nonsys),fill="grey80", stat = 'identity', color = 'grey80', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = nonsys + max(nonsys)*0.02, label =nonsys), 
              hjust = 1, size = 2.5) +
    scale_x_reverse(expand = expansion(mult = c(0.15, 0.00))) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'Number of NSMs', x = NULL, y = NULL) +
    theme_minimal()  +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.y = element_blank(),
      axis.text.x = element_text(size = 9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 0, 5, 5)
    )+geom_vline(xintercept = 0.5,linewidth=0.5)
  
  # ========== right: Mutations ==========
  p_right <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = Mutation), stat = 'identity',fill='#7fb3d5',
             color = '#7fb3d5', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = Mutation + 0.01, label =  Mutation), 
              hjust = 0, size = 2.5, fontface = 'bold') +
    scale_x_continuous(expand = expansion(mult = c(0, 0.1)),limits = c(0,1),labels = c(0,1),breaks = c(0,1)) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'HLAps mutation-drived', x = NULL, y = NULL) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 9),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 5, 5, 0)
    )
  
  p2=plot_grid(p_left,p_right)+plot_annotation(title = "PC organoids (n=11)")&  theme(plot.title = element_text(hjust = 0.5,face = "bold"))
}


#PDX
df=pep_mt[pep_mt$Disease=="PDX",]
df$Sample=factor(df$Sample,levels = rev(df$Sample))
df["CH-17-0049","Mutation"]=1#Mutation not grep
df["CH-17-0072","Mutation"]=0#Mutation not grep

{
  # ========== left: NSMs ==========
  p_left <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = nonsys),fill="grey80", stat = 'identity', color = 'grey80', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = nonsys + max(nonsys)*0.02, label =nonsys), 
              hjust = 1, size = 2.5) +
    scale_x_reverse(expand = expansion(mult = c(0.15, 0.0))) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'Number of NSMs', x = NULL, y = NULL) +
    theme_minimal()  +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.y = element_blank(),
      axis.text.x = element_text(size = 9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.x=element_line(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 0, 5, 5)
    )+geom_vline(xintercept = -70,linewidth=1)
  
  # ========== right: Mutations ==========
  p_right <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = Mutation), stat = 'identity',fill='#7fb3d5',
             color = '#7fb3d5', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = Mutation + 0.1, label =  Mutation), 
              hjust = 0, size = 2.5, fontface = 'bold') +
    scale_x_continuous(expand = expansion(mult = c(0, 0.2)),breaks = c(0,1,2),labels = c(0,1,2)) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'HLAps mutation-drived', x = NULL, y = NULL) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 9),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x=element_line(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 5, 5, 0)
    )
  
  p3=plot_grid(p_left,p_right)+plot_annotation(title = "CCA PDXs (n=13)")&  theme(plot.title = element_text(hjust = 0.5,face = "bold"))
}

#TCC
df=pep_mt[pep_mt$Disease=="TCC",]
df$Sample=factor(df$Sample,levels = rev(df$Sample))

{
  # ========== left: NSMs ==========
  p_left <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = nonsys),fill="grey80", stat = 'identity', color = 'grey80', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = nonsys + max(nonsys)*0.02, label =nonsys), 
              hjust = 1, size = 2.5) +
    scale_x_reverse(expand = expansion(mult = c(0.15, 0.0))) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'Number of NSMs', x = NULL, y = NULL) +
    theme_minimal()  +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.y = element_blank(),
      axis.text.x = element_text(size = 9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.x=element_line(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 0, 5, 5)
    )+geom_vline(xintercept = -70,linewidth=1)
  
  # ========== right: Mutations ==========
  p_right <- ggplot(df, aes(y = Sample)) +
    geom_bar(aes(x = Mutation), stat = 'identity',fill='#7fb3d5',
             color = '#7fb3d5', linewidth = 0.3, width = 0.6) +
    geom_text(aes(x = Mutation + 0.1, label =  Mutation), 
              hjust = 0, size = 2.5, fontface = 'bold') +
    scale_x_continuous(expand = expansion(mult = c(0, 0.2)),breaks = c(0:5),labels = c(0:5)) +
    coord_cartesian(ylim = c(0.5, length(df$Sample) + 0.5)) +
    labs(title = 'HLAps mutation-drived', x = NULL, y = NULL) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 9),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x=element_line(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5),
      plot.margin = margin(5, 5, 5, 0)
    )
  
  p4=plot_grid(p_left,p_right)+plot_annotation(title = "TC (n=3)")&  theme(plot.title = element_text(hjust = 0.5,face = "bold"))
}

plot_grid(p1,p2,p3,p4)

```


### fig.2B
```{r,warning=F,message=F,fig.height=5,fig.width=18}
library(openxlsx)
library(ComplexHeatmap)
library(circlize)
dat=read.xlsx("data/AllSample_Peptide_Canonical_NonCanonical_MsHLAp.xlsx")
dat$PST_N=rowSums(dat[,c("MS_PCA-01-PST","MS_PCA-02-PST","MS_PCA-03-PST","MS_PCA-04-PST",
                         "MS_PCA-05-PST","MS_PCA-06-PST")])
dat$TCC_N=rowSums(dat[,c("MS_TCC-01","MS_TCC-02","MS_TCC-03")])
dat$N=(dat$PST_N!=0)+(dat$DAC_N!=0)+(dat$PDX_N!=0)+(dat$TCC_N!=0)
ms_metastasis=c("MS_PCA-01-L1","MS_PCA-01-SCLN","MS_PCA-01-MLN","MS_PCA-01-PMI",
                  "MS_PCA-01-RMLN","MS_PCA-01-BDI","MS_PCA-01-SVI","MS_PCA-05-PVLN-L",
                  "MS_PCA-04-OBLN-L","MS_PCA-04-OBLN-R","MS_PCA-04-EILN","MS_PCA-06-CILN-L",
                  "MS_PCA-06-IILN-R")
grep_metastasis=c("grep_PCA-01-L1","grep_PCA-01-SCLN","grep_PCA-01-MLN","grep_PCA-01-PMI",
                    "grep_PCA-01-RMLN","grep_PCA-01-BDI","grep_PCA-01-SVI","grep_PCA-05-PVLN-L",
                    "grep_PCA-04-OBLN-L","grep_PCA-04-OBLN-R","grep_PCA-04-EILN","grep_PCA-06-CILN-L",
                    "grep_PCA-06-IILN-R")

ms_pst=c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST",
         "PCA-05-PST","PCA-06-PST")
ms_dac=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4","DAC5",
         "DAC50","DAC53","DAC57","DAC69")
ms_pdx=c("CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
         "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080",
         "CH-17-0087","CH-17-0091")
ms_tcc=c("TCC-01","TCC-02","TCC-03")

#set color
type_col=c("#FF7F0EFF","#1F77B4FF","#2CA02CFF","#F0E685FF","#9467BDFF","#8C564BFF","#466983FF","#D62728FF","#E377C2FF","#E377C2FF")
names(type_col)=c("BN","NCBI_Uniport","Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")

#metastatis

  pep1=dat$Peptide[dat$`source-annotated`=="Mutation"]
  
  ft=dat[is.element(dat$Peptide,pep1),]
  
  df_all=ft[,c(setdiff(colnames(ft),c(ms_metastasis,grep_metastasis)),ms_metastasis,grep_metastasis)]
  
  
  #2 diseases share
  {
    pep1=unique(df_all$Peptide[df_all$N==2])
    df=df_all[is.element(df_all$Peptide,pep1),]
    pep_ord=df[is.element(df$Peptide,pep1),c("Peptide",paste0("MS_",c(ms_pst,ms_dac,ms_pdx,ms_tcc)))]
    pep_ord[is.na(pep_ord)]=0
    pep_ord=pep_ord[rev(do.call(order,pep_ord[,-1])),]
    #pep_ord=pep_ord[rowSums(pep_ord[,grep("MS_",colnames(pep_ord))])>=2,]
    row_nm_2=pep_ord$Peptide
  }
  {
    pep1=unique(df_all$Peptide[df_all$N==1])
    df=df_all[is.element(df_all$Peptide,pep1),]
    pep_ord=df[is.element(df$Peptide,pep1),c("Peptide",paste0("MS_",c(ms_pst,ms_dac,ms_pdx,ms_tcc)))]
    pep_ord[is.na(pep_ord)]=0
    pep_ord=pep_ord[rev(do.call(order,pep_ord[,-1])),]
    #pep_ord=pep_ord[rowSums(pep_ord[,grep("MS_",colnames(pep_ord))])>=2,]
    row_nm_1=pep_ord$Peptide
  }
  {
    pep1=unique(df_all$Peptide[df_all$N==0])
    df=df_all[is.element(df_all$Peptide,pep1),]
    pep_ord=df[is.element(df$Peptide,pep1),c("Peptide",paste0("MS_",c(ms_pst,ms_dac,ms_pdx,ms_tcc)))]
    pep_ord[is.na(pep_ord)]=0
    pep_ord=pep_ord[rev(do.call(order,pep_ord[,-1])),]
    #pep_ord=pep_ord[rowSums(pep_ord[,grep("MS_",colnames(pep_ord))])>=2,]
    row_nm_0=pep_ord$Peptide
  }
######
row_nm1=c(row_nm_2,row_nm_1,row_nm_0)
  
df=df_all[is.element(df_all$Peptide,row_nm1),]
row_nm=c(row_nm1)
rownames(df)=df$Peptide
ht1=df[,c(grep("MS_",colnames(df)))]
colnames(ht1)=sub("MS_","",colnames(ht1))
ht1[is.na(ht1)]=0
    
ht2=df[,c(grep("grep_",colnames(df)))]
colnames(ht2)=sub("grep_","",colnames(ht2))
ht2[ht2==0]=""
ht2[!is.na(ht2)&ht2!=""]="*"
ht2[is.na(ht2)]=""
    
MS_ht=ht1[row_nm,]
MS_ht[is.na(MS_ht)]=0
MS_ht[MS_ht!=0]=1
cell_dt=ht2[row_nm,]
    
MS_ht1=MS_ht[,c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST","PCA-05-PST","PCA-06-PST")]
MS_ht2=MS_ht[,7:17]
MS_ht3=MS_ht[,18:30]
MS_ht4=MS_ht[,32:34]
MS_ht6=MS_ht[,1,drop=F]
    
cell_dt1=cell_dt[,c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST","PCA-05-PST","PCA-06-PST")]
cell_dt2=cell_dt[,7:17]
cell_dt3=cell_dt[,18:30]
cell_dt4=cell_dt[,32:34]
cell_dt6=cell_dt[,1,drop=F]
    
anot_ht1=df[row_nm,c("CEDAR","IEDB","HLAthena","RNA","Protein")]
anot_ht1[anot_ht1==TRUE]=1
anot_ht1[anot_ht1==FALSE]=0
anot_ht2=df[row_nm,c("cancer_restricted"),drop=F]
anot_ht2[anot_ht2==TRUE]=1
anot_ht2[anot_ht2==FALSE]=0
    
IPS_ht=df[row_nm,c("ASPC1_G517_WG630","ELISPOT","RNA_fish"),drop=F]
IPS_ht$RNA_fish=ifelse(IPS_ht$RNA_fish=="Yes",1,0)
IPS_ht[is.na(IPS_ht)]=0
    
anot_ht4=df[row_nm,c("PublicPaper"),drop=F]
    
exp_ht=df[row_nm,c("source-annotated","Gene"),drop=F]
exp_ht[is.na(exp_ht)]=""
    
hr1=rowAnnotation(Source=exp_ht$`source-annotated`,
                      col=list(Source=type_col),
                      gp = gpar(col = "black"),
                      gap = unit(4, "points"),simple_anno_size=unit(2,"mm"),
                      annotation_name_side = "top")
hr4=rowAnnotation(SCI=anno_barplot(df[row_nm,"SCI"],axis_param = list(side="top"),gp = gpar(fill="#3B4992FF")),
                      PublicPaper=anno_barplot(df[row_nm,"PublicPaper"],axis_param = list(side="top",at=c(0,1)),gp = gpar(fill="#3B4992FF")),
                      Gene=anno_text(exp_ht$Gene,gp=gpar(fontsize=6)),
                      gap = unit(4, "points"),simple_anno_size=unit(2,"mm"),
                      annotation_name_side = "top",annotation_name_rot=90)
    
plt1=Heatmap(cbind(MS_ht1,MS_ht2,MS_ht3,MS_ht4,MS_ht6),col = c("white","#4DBBD5FF"),cluster_rows = F,cluster_columns = F,row_labels = df[row_nm,"Peptide"],column_names_side = "top",
                 right_annotation = hr1,column_names_gp = gpar(fontsize=7),row_names_gp = gpar(fontsize=7),row_names_side = "left",
                 show_row_names = T,rect_gp = gpar(col="black"),show_row_dend = F,row_title_rot = 0,row_title_gp = gpar(fontsize=8),name="MS",
                 row_split =factor(df[row_nm,c("source-annotated")],levels =c("NCBI_Uniport","Mutation","Fusion","IR","TElocal","TEprof2",
                                                                              "DN","Cis","Trans")),
                 cell_fun=function(j, i,x,y,  width, height, fill) {
                   # since grid.text can also be vectorized
                   grid.text(as.matrix(cbind(cell_dt1,cell_dt2,cell_dt3,cell_dt4,cell_dt6))[i,j], x, y,hjust=0.5,vjust=0.8 ,
                             gp = gpar(fontsize = 8))},
                 column_split = factor(c(rep("Primary PCa",ncol(MS_ht1)),rep("PC organoids",ncol(MS_ht2)),rep("CCA PDXs",ncol(MS_ht3)),rep("TC",ncol(MS_ht4)),""),
                                       levels=c("Primary PCa","PC organoids","CCA PDXs","TC","")),
                 height = unit(nrow(MS_ht)*0.25,"cm"),width = unit(ncol(MS_ht)*0.22,"cm"),
                 heatmap_legend_param = list(border="black"),border=T,column_title_gp = gpar(fontsize=8,fontface="bold"))
    
anot_plt1=Heatmap(anot_ht1,col = c("0"="white","1"="#00b6a5"),cluster_rows = F,cluster_columns = F,rect_gp = gpar(col="black"),row_labels = df[row_nm,"Peptide"],column_names_side = "top",
                      column_names_gp = gpar(fontsize=7),row_names_gp = gpar(fontsize=7),row_names_side = "left",
                      show_row_names = T,show_row_dend = F,row_title_rot = 0,row_title_gp = gpar(fontsize=8),name="MS",
                      na_col = "white",
                      height = unit(nrow(MS_ht)*0.25,"cm"),width = unit(ncol(anot_ht1)*0.25,"cm"))
anot_plt2=Heatmap(anot_ht2,col = c("0"="white","1"="#e75640"),cluster_rows = F,cluster_columns = F,rect_gp = gpar(col="black"),row_labels = df[row_nm,"Peptide"],column_names_side = "top",
                      column_names_gp = gpar(fontsize=7),row_names_gp = gpar(fontsize=7),row_names_side = "left",
                      show_row_names = T,show_row_dend = F,row_title_rot = 0,row_title_gp = gpar(fontsize=8),name="MS",
                      na_col = "white",
                      height = unit(nrow(MS_ht)*0.25,"cm"),width = unit(ncol(anot_ht2)*0.25,"cm"))
    
IPS_plt=Heatmap(IPS_ht,col = c("0"="white","1"="#766cb1"),cluster_rows = F,cluster_columns = F,rect_gp = gpar(col="black"),row_labels = df[row_nm,"Peptide"],column_names_side = "top",
                    column_names_gp = gpar(fontsize=7),row_names_gp = gpar(fontsize=7),row_names_side = "left",
                    show_row_names = T,show_row_dend = F,row_title_rot = 0,row_title_gp = gpar(fontsize=8),name="MS",
                    right_annotation = hr4,height = unit(nrow(MS_ht)*0.25,"cm"),width = unit(0.75,"cm"))
    
#pdf(paste("Fig2B.pdf",sep=""),height=5,width =18)
plt1+anot_plt1+anot_plt2+IPS_plt
#dev.off()
```

### fig.2C
```{r,warning=F,message=F,fig.height = 3,fig.width = 15}
library(openxlsx)
library(ggplot2)

ms_pst=c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST",
         "PCA-05-PST","PCA-06-PST")
ms_dac=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4","DAC5",
         "DAC50","DAC53","DAC57","DAC69")
ms_pdx=c("CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
         "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080",
         "CH-17-0087","CH-17-0091")
ms_tcc=c("TCC-01","TCC-02","TCC-03")

peptide_stat=read.xlsx("data/FigS3_data.xlsx",rowNames = T)
stat_df=as.data.frame(t(peptide_stat))
stat_df$ncHLAp=rowSums(stat_df[,c("Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")])
stat_df$Canonical_HLAp=stat_df[,c("Mutation")]

#Prostate+Pri_Meta
rownames(stat_df)=sub("MS_","",rownames(stat_df))
stat_df$Samples=rownames(stat_df)
stat_df$Disease=c(rep("Prostate",16),rep("DAC",11),rep("PDX",13),rep("Prostate",3),
                  rep("TCC",3))
stat_df$type=c("Primary",rep("metastasis",7),rep("Primary",2),"metastasis","Primary",rep("metastasis",3),
               rep("Primary",26),rep("metastasis",2),rep("Primary",3))
#Prostate_Pri
{
  stat_dt=stat_df[stat_df$Disease=="Prostate"&stat_df$type=="Primary",c("ncHLAp","Canonical_HLAp","Samples")]
  stat_dt$allHLAp=stat_dt$ncHLAp+stat_dt$Canonical_HLAp
  stat_dt$ncHLAp=stat_dt$ncHLAp/stat_dt$allHLAp
  stat_dt$Canonical_HLAp=stat_dt$Canonical_HLAp/stat_dt$allHLAp
  
  plot_df=melt(stat_dt[,c("ncHLAp","Canonical_HLAp","Samples")])
  pst_pri=plot_df
  p1=ggplot(plot_df,aes(x=Samples,y=value))+geom_col(aes(fill=variable))+
    theme_classic()+
    theme(
      plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 8,angle = 90,vjust=0.5,hjust=1),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x = element_line(),
      axis.title.y = element_text(size=9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5)
    )+scale_y_continuous(expand = c(0,0),breaks=seq(0,1,by=0.25),labels = seq(0,100,by=25))+
    scale_fill_manual(values=c("ncHLAp"="#DB8577","Canonical_HLAp"='grey80'))+
    ylab("% of peptides uniquely mapped \nto canonical genes or nuORFs")+xlab("")+
    ggtitle("Prostate PCa")
}

#DAC
  stat_dt=stat_df[stat_df$Disease=="DAC",c("ncHLAp","Canonical_HLAp","Samples")]
  stat_dt$allHLAp=stat_dt$ncHLAp+stat_dt$Canonical_HLAp
  stat_dt$ncHLAp=stat_dt$ncHLAp/stat_dt$allHLAp
  stat_dt$Canonical_HLAp=stat_dt$Canonical_HLAp/stat_dt$allHLAp
  
  plot_df=melt(stat_dt[,c("ncHLAp","Canonical_HLAp","Samples")])
  plot_df$Samples=factor(plot_df$Samples,levels = unique(plot_df$Samples))
  dac=plot_df
  p2=ggplot(plot_df,aes(x=Samples,y=value))+geom_col(aes(fill=variable))+
    theme_classic()+
    theme(
      plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 8,angle = 90,vjust=0.5,hjust=1),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x = element_line(),
      axis.title.y = element_text(size=9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5)
    )+scale_y_continuous(expand = c(0,0),breaks=seq(0,1,by=0.25),labels = seq(0,100,by=25))+
    scale_fill_manual(values=c("ncHLAp"="#DB8577","Canonical_HLAp"="grey80"))+
    ylab("% of peptides uniquely mapped \nto canonical genes or nuORFs")+xlab("")+
    ggtitle("PC organoids")

#PDX

  stat_dt=stat_df[,c("ncHLAp","Canonical_HLAp","Samples","Disease")]
  stat_dt$allHLAp=stat_dt$ncHLAp+stat_dt$Canonical_HLAp
  stat_dt$ncHLAp=stat_dt$ncHLAp/stat_dt$allHLAp
  stat_dt$Canonical_HLAp=stat_dt$Canonical_HLAp/stat_dt$allHLAp
  
  plot_df=melt(stat_dt[stat_dt$Disease=="PDX",c("ncHLAp","Canonical_HLAp","Samples","Disease")])
  plot_df$Samples=factor(plot_df$Samples,levels = unique(plot_df$Samples))
  pdx=plot_df
  p3=ggplot(plot_df,aes(x=Samples,y=value))+geom_col(aes(fill=variable))+
    theme_classic()+
    theme(
      plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 8,angle = 90,vjust=0.5,hjust=1),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x = element_line(),
      axis.title.y = element_text(size=9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5)
    )+scale_y_continuous(expand = c(0,0),breaks=seq(0,1,by=0.25),labels = seq(0,100,by=25))+
    scale_fill_manual(values=c("ncHLAp"="#DB8577","Canonical_HLAp"="grey80"))+
    ylab("% of peptides uniquely mapped \nto canonical genes or nuORFs")+xlab("")+
    ggtitle("CAA PDXs")

#TC
  stat_dt=stat_df[,c("ncHLAp","Canonical_HLAp","Samples","Disease")]
  stat_dt$allHLAp=stat_dt$ncHLAp+stat_dt$Canonical_HLAp
  stat_dt$ncHLAp=stat_dt$ncHLAp/stat_dt$allHLAp
  stat_dt$Canonical_HLAp=stat_dt$Canonical_HLAp/stat_dt$allHLAp
  
  plot_df=melt(stat_dt[stat_dt$Disease=="TCC",c("ncHLAp","Canonical_HLAp","Samples","Disease")])
  plot_df$Samples=factor(plot_df$Samples,levels = unique(plot_df$Samples))
  tcc=plot_df
  p4=ggplot(plot_df,aes(x=Samples,y=value))+geom_col(aes(fill=variable))+
    theme_classic()+
    theme(
      plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                margin = margin(b = 10)),
      axis.text.x = element_text(size = 8,angle = 90,vjust=0.5,hjust=1),
      axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
      axis.ticks.x = element_line(),
      axis.title.y = element_text(size=9),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = 'black', linewidth = 0.5),
      axis.line.y = element_line(color = 'black', linewidth = 0.5)
    )+scale_y_continuous(expand = c(0,0),breaks=seq(0,1,by=0.25),labels = seq(0,100,by=25))+
    scale_fill_manual(values=c("ncHLAp"="#DB8577","Canonical_HLAp"="grey80"))+
    ylab("% of peptides uniquely mapped \nto canonical genes or nuORFs")+xlab("")+
    ggtitle("TC")


plot_leg=get_legend(p4)
#pdf("res/Fig2C_allDisease_ncHLAp_cHLAp.pdf",height = 3,width = 15)
plot_grid(p1+theme(legend.position = "none"),p2+theme(legend.position="none"),align = "hv",
          p3+theme(legend.position="none"),p4+theme(legend.position="none"),axis = "tblr",
          plot_leg,nrow=1,
          rel_widths = c(0.4,0.6,0.68,0.29,0.4))
#dev.off()

#pst_pri$Disease="PST_Primary"
#dac$Disease="PC organoids"
#fig2C_df=rbind(pst_pri[,colnames(tcc)],pdx,dac[,colnames(tcc)],tcc)
#stat_mt=dcast(fig2C_df,Samples+Disease~variable,value.var = "value")
#write.xlsx(stat_mt,"fig2C_data.xlsx")
```

### fig.2D
```{r,warning=F,message=F,fig.height = 2.5,fig.width = 16}
library(ggplot2)
library(openxlsx)
library(dplyr)
type_col=c("#1F77B4FF","#FF7F0EFF","#2CA02CFF","#F0E685FF","#9467BDFF","#8C564BFF","#466983FF","#D62728FF","#E377C2FF","#5DB1DDFF") 
names(type_col)=c("Benign","Uniport","Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")
dat=read.xlsx("data/AllSample_Peptide_Canonical_NonCanonical_MsHLAp.xlsx")
dat$ncHLAp=ifelse(dat$`source-annotated`=="Mutaiton","Canonical_HLAp","ncHLAp")
dat$PST_N=rowSums(dat[,c("MS_PCA-01-PST","MS_PCA-02-PST","MS_PCA-03-PST","MS_PCA-04-PST",
                         "MS_PCA-05-PST","MS_PCA-06-PST")])

{
  plot_df=dat[dat$PST_N>0,]%>%
    group_by(`source-annotated`)%>%summarise(N=length(unique(Peptide)))
  plot_df$Var1=factor(plot_df$`source-annotated`,levels = rev(c("Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")))
  p1=ggplot(plot_df,aes(x=N,y=Var1,fill=Var1))+geom_col()+
    scale_fill_manual(values=type_col)+
    guides(fill=guide_legend(reverse = T,title="Source Annotated",ncol = 2))+
    geom_text(aes(label = N),hjust=-0.1,size = 2.3, fontface = 'bold')+
    xlab("No. of ncHLAps")+
    theme_pubr()+
    theme(legend.position = "right",
          axis.text.x = element_text(size = 9),
          axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
          axis.line.x = element_line(color = 'black', linewidth = 0.5),
          axis.line.y = element_line(color = 'black', linewidth = 0.5),
          plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                    margin = margin(b = 10)))+ylab("")+
    scale_x_continuous(expand = expansion(mult = c(0, 0.1)))+
    ggtitle("Prostate PCa")
}

{
  plot_df=dat[dat$DAC_N>0,]%>%
    group_by(`source-annotated`)%>%summarise(N=length(unique(Peptide)))
  plot_df$Var1=factor(plot_df$`source-annotated`,levels = rev(c("Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")))
  plot_df=plot_df[,c("Var1","N")]
  plot_df=rbind(plot_df,data.frame(Var1=setdiff(c("Fusion","IR","TElocal","TEprof2","DN","Cis","Trans"),unique(plot_df$Var1)),N=0))
  
  p2=ggplot(plot_df,aes(x=N,y=Var1,fill=Var1))+geom_col()+
    scale_fill_manual(values=type_col)+
    guides(fill=guide_legend(reverse = T,title="Source Annotated",ncol = 2))+
    geom_text(aes(label = N),hjust=-0.1,size = 2.3, fontface = 'bold')+
    xlab("No. of ncHLAps")+
    theme_pubr()+
    theme(legend.position = "right",
          axis.text.x = element_text(size = 9),
          axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
          axis.line.x = element_line(color = 'black', linewidth = 0.5),
          axis.line.y = element_line(color = 'black', linewidth = 0.5),
          plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                    margin = margin(b = 10)))+ylab("")+
    scale_x_continuous(expand = expansion(mult = c(0, 0.1)))+
    ggtitle("PC organoids")
}
{
  plot_df=dat[dat$PDX_N>0,]%>%
    group_by(`source-annotated`)%>%summarise(N=length(unique(Peptide)))
  plot_df$Var1=factor(plot_df$`source-annotated`,levels = rev(c("Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")))
  plot_df=plot_df[,c("Var1","N")]
  plot_df=rbind(plot_df,data.frame(Var1=setdiff(c("Fusion","IR","TElocal","TEprof2","DN","Cis","Trans"),unique(plot_df$Var1)),N=0))
  
  p3=ggplot(plot_df,aes(x=N,y=Var1,fill=Var1))+geom_col()+
    scale_fill_manual(values=type_col)+
    guides(fill=guide_legend(reverse = T,title="Source Annotated",ncol = 2))+
    geom_text(aes(label = N),hjust=-0.1,size = 2.3, fontface = 'bold')+
    xlab("No. of ncHLAps")+
    theme_pubr()+
    theme(legend.position = "right",
          axis.text.x = element_text(size = 9),
          axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
          axis.line.x = element_line(color = 'black', linewidth = 0.5),
          axis.line.y = element_line(color = 'black', linewidth = 0.5),
          plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                    margin = margin(b = 10)))+ylab("")+
    scale_x_continuous(expand = expansion(mult = c(0, 0.1)))+
    ggtitle("CCA PDXs")
}
{
  plot_df=dat[dat$TCC_N>0,]%>%
    group_by(`source-annotated`)%>%summarise(N=length(unique(Peptide)))
  plot_df$Var1=factor(plot_df$`source-annotated`,levels = rev(c("Mutation","Fusion","IR","TElocal","TEprof2","DN","Cis","Trans")))
  plot_df=plot_df[,c("Var1","N")]
  plot_df=rbind(plot_df,data.frame(Var1=setdiff(c("Fusion","IR","TElocal","TEprof2","DN","Cis","Trans"),unique(plot_df$Var1)),N=0))
  
  p4=ggplot(plot_df,aes(x=N,y=Var1,fill=Var1))+geom_col()+
    scale_fill_manual(values=type_col)+
    guides(fill=guide_legend(reverse = T,title="Source Annotated",ncol = 2))+
    geom_text(aes(label = N),hjust=-0.1,size = 2.3, fontface = 'bold')+
    xlab("No. of ncHLAps")+
    theme_pubr()+
    theme(legend.position = "right",
          axis.text.x = element_text(size = 9),
          axis.text.y = element_text(hjust=0.5,vjust=0.5,size = 8),
          axis.line.x = element_line(color = 'black', linewidth = 0.5),
          axis.line.y = element_line(color = 'black', linewidth = 0.5),
          plot.title = element_text(hjust = 0.5, size = 12, face = 'bold',
                                    margin = margin(b = 10)))+ylab("")+
    scale_x_continuous(expand = expansion(mult = c(0, 0.1)))+
    ggtitle("TC")
}

plot_leg=get_legend(p4)
#pdf("Fig2D_allDisease_ncHLAp_HLAcheck.pdf",height = 2.5,width = 16)
plot_grid(p1+theme(legend.position = "none"),p2+theme(legend.position="none"),
          p3+theme(legend.position="none"),p4+theme(legend.position="none"),
          plot_leg,nrow=1,rel_widths = c(1,1,1,1,0.8))
#dev.off()
```

### Fig.2E
```{r,warning=F,message=F,fig.width = 30,fig.height = 4}
library(openxlsx)
library(cowplot)
library(ggplot2)
library(reshape2)
ms_pst=c("PCA-01-PST","PCA-02-PST","PCA-03-PST","PCA-04-PST",
         "PCA-05-PST","PCA-06-PST")
ms_dac=c("DAC13","DAC71","DAC73","DAC22","DAC30","DAC4","DAC5",
         "DAC50","DAC53","DAC57","DAC69")
ms_pdx=c("CH-17-0036","CH-17-0049","CH-17-0053","CH-17-0060","CH-17-0061","CH-17-0064",
         "CH-17-0068","CH-17-0070","CH-17-0072","CH-17-0074","CH-17-0080",
         "CH-17-0087","CH-17-0091")
ms_tcc=c("TCC-01","TCC-02","TCC-03")

df=read.xlsx("data/AllSample_Peptide_Canonical_NonCanonical_MsHLAp.xlsx")
DN_peptide=df[df$`source-annotated`=="DN",]

dn_orf_res=read.xlsx("data/DN_orf_annotation_LC_V44_reviwerpriority.xlsx")

#by diseases
pep1=DN_peptide$Peptide[DN_peptide$Multimapping==F&rowSums(DN_peptide[,paste0("MS_",ms_pst)])>0]
pep2=DN_peptide$Peptide[DN_peptide$Multimapping==F&rowSums(DN_peptide[,paste0("MS_",ms_dac)])>0]
pep3=DN_peptide$Peptide[DN_peptide$Multimapping==F&rowSums(DN_peptide[,paste0("MS_",ms_pdx)])>0]
pep4=DN_peptide$Peptide[DN_peptide$Multimapping==F&rowSums(DN_peptide[,paste0("MS_",ms_tcc)])>0]

#Primary
Region_lev=c("InternalORF","ncRNA","5'UTR","3'UTR","LowConfidence\nExon","IGR","uORF","5_extension","dORF")
Region_col=c("#57b1d4","#9ed9e9","#55b85d","#b2d59b","#e2e560","#e9eca9","#dc8d42","#ddba90","#626dad")
names(Region_col)=Region_lev

#Primary PCa
dn_orf_res$primary_annotation[dn_orf_res$primary_annotation=="LowConfidence_Exon"]="LowConfidence\nExon"
plot_df=as.data.frame(table(dn_orf_res$primary_annotation[is.element(dn_orf_res$peptide,pep1)]))
plot_df$freq=plot_df$Freq/sum(plot_df$Freq)
colnames(plot_df)[1]="Region"
plot_df=rbind(plot_df,data.frame(Region=setdiff(Region_lev,unique(plot_df$Region)),
                                 Freq=0,freq=0))
plot_df$Region=factor(plot_df$Region,levels = rev(Region_lev))
plot_df$label=paste(plot_df$Freq,"(",round(plot_df$freq,2)*100,"%)",sep="")
plot_df1=plot_df[order(plot_df$Region),]

p1=ggplot(plot_df1,aes(y=Region,x=freq,fill=Region))+geom_col(alpha=0.8)+
  geom_text(aes(label=label),vjust=0.5,size=3,hjust=-0.1)+
  theme_classic()+
  theme(axis.text.y = element_text(angle=0,vjust=0.5,hjust=1),
        plot.title = element_text(size = 14, face = 'bold', hjust = 0.5))+
  scale_fill_manual(values = Region_col)+
  xlab("% of ncHLAp")+ylab("")+
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels = c(0,10,20,30,40,50,60),
                     expand =expansion(mult = c(0, 0.2)))+
  ggtitle(paste0("Primary PCa(",length(pep1),")"))

#PC organoids
plot_df=as.data.frame(table(dn_orf_res$primary_annotation[is.element(dn_orf_res$peptide,pep2)]))
plot_df$freq=plot_df$Freq/sum(plot_df$Freq)
colnames(plot_df)[1]="Region"
plot_df=rbind(plot_df,data.frame(Region=setdiff(Region_lev,unique(plot_df$Region)),
                                 Freq=0,freq=0))
plot_df$Region=factor(plot_df$Region,levels = rev(Region_lev))
plot_df$label=paste(plot_df$Freq,"(",round(plot_df$freq,2)*100,"%)",sep="")
plot_df2=plot_df[order(plot_df$Region),]

p2=ggplot(plot_df2,aes(y=Region,x=freq,fill=Region))+geom_col(alpha=0.8)+
  geom_text(aes(label=label),vjust=0.5,size=3,hjust=-0.1)+
  theme_classic()+
  theme(axis.text.y = element_text(angle=0,vjust=0.5,hjust=1),
        plot.title = element_text(size = 14, face = 'bold', hjust = 0.5))+
  scale_fill_manual(values = Region_col)+
  xlab("% of ncHLAp")+ylab("")+
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels = c(0,10,20,30,40,50,60),
                     expand =expansion(mult = c(0, 0.25)))+
  ggtitle(paste0("PC organoids(",length(pep2),")"))

#CCA PDXs
plot_df=as.data.frame(table(dn_orf_res$primary_annotation[is.element(dn_orf_res$peptide,pep3)]))
plot_df$freq=plot_df$Freq/sum(plot_df$Freq)
colnames(plot_df)[1]="Region"
plot_df$Region=factor(plot_df$Region,levels = rev(Region_lev))
plot_df$label=paste(plot_df$Freq,"(",round(plot_df$freq,2)*100,"%)",sep="")
plot_df3=plot_df[order(plot_df$Region),]

p3=ggplot(plot_df3,aes(y=Region,x=freq,fill=Region))+geom_col(alpha=0.8)+
  geom_text(aes(label=label),vjust=0.5,size=3,hjust=-0.1)+
  theme_classic()+
  theme(axis.text.y = element_text(angle=0,vjust=0.5,hjust=1),
        plot.title = element_text(size = 14, face = 'bold', hjust = 0.5))+
  scale_fill_manual(values = Region_col)+
  xlab("% of ncHLAp")+ylab("")+
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels = c(0,10,20,30,40,50,60),
                     expand =expansion(mult = c(0, 0.2)))+
  ggtitle(paste0("CCA PDXs(",length(pep3),")"))

#TC
plot_df=as.data.frame(table(dn_orf_res$primary_annotation[is.element(dn_orf_res$peptide,pep4)]))
plot_df$freq=plot_df$Freq/sum(plot_df$Freq)
colnames(plot_df)[1]="Region"
plot_df=rbind(plot_df,data.frame(Region=setdiff(Region_lev,unique(plot_df$Region)),
                                 Freq=0,freq=0))
plot_df$Region=factor(plot_df$Region,levels = rev(Region_lev))
plot_df$label=paste(plot_df$Freq,"(",round(plot_df$freq,2)*100,"%)",sep="")
plot_df4=plot_df[order(plot_df$Region),]

p4=ggplot(plot_df4,aes(y=Region,x=freq,fill=Region))+geom_col(alpha=0.8)+
  geom_text(aes(label=label),vjust=0.5,size=3,hjust=-0.1)+
  theme_classic()+
  theme(axis.text.y = element_text(angle=0,vjust=0.5,hjust=1),
        plot.title = element_text(size = 14, face = 'bold', hjust = 0.5))+
  scale_fill_manual(values = Region_col)+guides(fill=guide_legend(reverse = T))+
  xlab("% of ncHLAp")+ylab("")+
  scale_x_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels = c(0,10,20,30,40,50,60),
                     expand =expansion(mult = c(0, 0.25)))+
  ggtitle(paste0("TC(",length(pep4),")"))

lgd=get_legend(p3)
#pdf("Fig2E_DN_ORF_barplot_byDisease_reviwerpriority.pdf",width = 30,height = 4)
plot_grid(p1+theme(legend.position = "none"),
          p2+theme(legend.position = "none"),
          p3+theme(legend.position = "none"),
          p4+theme(legend.position = "none"),
          lgd,nrow=1,align = "hv",rel_widths = c(1,1,1,1,0.5))
#dev.off()

#plot_alldf=rbind(plot_df1,plot_df2,plot_df3,plot_df4)
#plot_alldf$Disease=c(rep("Primary PCa",nrow(plot_df1)),
#                     rep("PC organoids",nrow(plot_df2)),
#                     rep("CCA PDXs",nrow(plot_df3)),
#                     rep("TC",nrow(plot_df4)))
#write.xlsx(plot_alldf,"Fig2E_DN_ORF_barplot_byDisease_reviwerpriority_data.xlsx")
```

